### ISSUE TITLE
Looking for maintainer: SoftLayer

### ISSUE THREAD

**Issue by jamielennox** [StackExchange/dnscontrol#656] opened 2020-02-24 03:27 UTC
I contributed and successfully used this provider for a project that was based on IBM Cloud/Bluemix/Softlayer and as far as I know it's continued to work fine. 

I have since changed jobs and no longer have access to the SoftLayer APIs (I don't think it's just something you can get free access to) and so am unable to maintain this any further. There are only one or two issues (#583 the only that comes to mind) that I assume are easy to fix but it's not something I can do any longer. 

I see other providers are starting to be marked going away in 3.0 (#653) and I suggest unless someone steps up we should do the same thing to SoftLayer.

**Comment by jamielennox** [comment] 2020-02-24 03:30
Umm, maybe @nibalizer or @stevemar could point someone out?

**Comment by stevemar** [comment] 2020-02-24 14:33
@jamielennox let me ask around, thanks for the heads up.

**Comment by captncraig** [comment] 2020-02-24 15:04
IIRC, you can use the DNS by making an account and making a storage account
or something like that and just not use it. You will get a zero dollar
invoice each month, but that is sufficient to test DNS.

**Comment by saurabhguptag** [comment] 2020-02-28 10:14
I could take up. But expect Delayed response.

**Comment by tlimoncelli** [comment] 2020-03-02 16:27
@saurabhguptag 

> I could take up. But expect Delayed response.

We'd appreciate it if you took over ownership!

**Comment by tlimoncelli** [comment] 2022-03-01 15:56
Closing. Duplicate of https://github.com/StackExchange/dnscontrol/issues/1079

**Closed by tlimoncelli** 2022-03-01 15:56 UTC
Labels: Type: Maintenance, Priority: p3 - Low
