### ISSUE TITLE
2FA problematic with INWX

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#848] opened 2020-09-05 03:11 UTC
I'm currently trying to migrate to INWX and take use of the great implementation by @svenpeter42. In my setup I'm using the `totp-key` (encrypted, etc) option, which seems to basically generate the TOTP during runtime just fine (verified by stepping through the code).

But at some point it seems that the TOTP is not valid anymore for some reason, see below. Absolutely nothing changed between the executions, just a few seconds passed by. So it might be a timing issue. Was someone able to see the same behavior?

See:
```
$ date; dnscontrol preview --domains domain.tld; echo
Sat Sep  5 04:03:21 BST 2020
INWX: Could not unlock account: (2200) Authentication error. Reason: (INVALID) The confirmation code is invalid.

$ date; dnscontrol preview --domains domain.tld; echo
Sat Sep  5 04:03:27 BST 2020
INWX: Could not unlock account: (2200) Authentication error. Reason: (INVALID) The confirmation code is invalid.

$ date; dnscontrol preview --domains domain.tld; echo
Sat Sep  5 04:03:32 BST 2020
******************** Domain: domain.tld
----- Getting nameservers from: inwx
----- DNS Provider: inwx...0 corrections
----- Registrar: inwx...ERROR
Error getting corrections: Error 404: "This service does not exist" <------ means that the login worked fine however
Done. 0 corrections.
completed with errors
```

What I can further rule out:
- The TOTP codes generated from dnscontrol are working fine, as I can use them to login in the WebUI just fine. So the basic functionality works.
- I can rule out local time drifts on my machine: 1) TOTP codes generated from my local password manager works, 2) checked time and regularly syncing it with NTP servers.
- Without 2-Factor-Authentication all authentications work fine, so it seems to be TOTP-related.

**Comment by svenpeter42** [comment] 2020-09-05 11:23
I think I know what's happening. INWX will only accept a single TOTP code once. This means you can only login once every 30 seconds.

Do you have INWX setup as both the registrar and the DNS provider? If so, dnscontrol will probably try to login twice within a few seconds. The first login will work fine but the second login will try to use the same TOTP code and will then fail. I'll have to think if there's an easy way to reuse an already existing session to work around that issue.

**Comment by patschi** [comment] 2020-09-05 14:24
I assumed something like that too (but rather inwx overwriting session or so) - haven't mentioned that and edited that wrong in the output above, apologies. I've noticed this also as the code stepped through getOtp twice during runtime. 

> Can you check what happens if you only setup INWX as the DNS provider and use a dummy registrar?

That's what I did in the tests above. I've used a dummy registrar and only used dns provider.

**Comment by svenpeter42** [comment] 2020-09-05 17:11
The invalid OTP error probably has the same cause: notice how it fails when the current second is 2X but suddenly starts working once you pass 30 seconds. You’ve probably logged in a few seconds earlier and the TOTP code for xx:00-xx:29 is considered ‚invalid‘. I also don’t see any way to fix this except for explaining this as a possible failure cause in an error message.

It might be possible to fix the problem when using INWX as registrar and dns provider at the same time though by adding a session cache. That‘s probably going to be a little bit ugly though.
There’s also an even uglier solution: usually codes with an offset of up to one minute or so are accepted so I could just generate a code 30s from the past/future the second time but I’d very much like to avoid that.

That 404 error once it works is rather strange though and I’m not able to reproduce it. Can you check which API call returns that?

**Comment by patschi** [comment] 2020-09-05 17:26
Sounds plausible, indeed... When I wait ~30 seconds between each execution, it seems to work fine:
```sh
$ while true; do date; dnscontrol preview --domains domain.tld; echo; sleep 30; done
```

| Date | Status |
| ---- | ------ |
| Sat Sep  5 18:19:13 BST 2020 | OK |
| Sat Sep  5 18:19:46 BST 2020 | OK |
| Sat Sep  5 18:20:18 BST 2020 | OK |
| Sat Sep  5 18:20:51 BST 2020 | OK |
| Sat Sep  5 18:21:24 BST 2020 | OK |
| Sat Sep  5 18:21:57 BST 2020 | OK |
| Sat Sep  5 18:22:29 BST 2020 | OK |
| Sat Sep  5 18:23:02 BST 2020 | OK |
| Sat Sep  5 18:23:35 BST 2020 | OK |
| Sat Sep  5 18:24:08 BST 2020 | OK |

I wonder what the reason on INWX side is by doing that... IMHO: Even when TOTP is used twice, it's still valid and should be accepted.

> That 404 error once it works is rather strange though and I’m not able to reproduce it.

You can completely ignore that bit. I'm using a different registrar than INWX while the domain is registered at INWX, just for testing purposes (to prevent double-logins).

**Comment by svenpeter42** [comment] 2020-09-05 18:02
There’s arguably a (small) security benefit to preventing reuse of the same code: you need an active MITM attacker to hijack the session instead of just sniffing traffic and reusing the code to create a secondary session.

I’ll add a hint to the error message about this behavior and I’ll also think about a way to support INWX as registrar and dns provider simultaneously when TOTP is enabled.

**Comment by patschi** [comment] 2020-09-07 23:10
> There’s arguably a (small) security benefit to preventing reuse of the same code

I've wrote an email to INWX, just to get official clarification on this. tl;dr and spoiler: You were right. It's considered as a security benefit. 

The friendly man of the INWX brought up the example when someone stands next to you and might re-use the TAN/TOTP to login.  But I'm not really sure how said person should my extra-long and complex, random generated password from my password manager first, without me noticing. (Beside that I can imagine that this limitation has also legacy reasons.)

He also brought up the same idea you had earlier: Using 2 different TOTP codes, one from ~30secs ago, and from the current time to get past this limitation.

**Comment by patschi** [comment] 2020-09-14 20:15
Just to add: I've had a nice chat with the INWX support and they told me that it's possible to create subaccounts to have separate access to the account, e.g. a dedicated account for API access, where 2FA could be disabled. However this needs to be done manually via their support.

**Comment by tlimoncelli** [comment] 2020-09-14 21:53
> However this needs to be done manually via their support.

Great to hear!  Can you update the `docs/_providers/inwx.md` doc?  I think others will find that useful.

**Comment by svenpeter42** [comment] 2020-09-20 13:49
I didn't even think of contacting the INWX support. Great idea! I've added this to the documentation. 

I think using this scoped subaccount is the best way to support 2fa on the master account and still use dnscontrol with INWX. I think we can close this issue then.

**Comment by tlimoncelli** [comment] 2020-09-20 14:38
May I close this ticket?

**Comment by svenpeter42** [comment] 2020-09-20 19:53
fine with me. how about you, @patschi ?

**Comment by patschi** [comment] 2020-09-20 20:29
Fine with me too. Probably an new issue for tracking "re-using session"-feature for INWX might be helpful? (feature request?)

**Closed** 2020-10-12 16:20 UTC
