### ISSUE TITLE
PowerDNS occasionally fails

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1148] opened 2021-05-07 18:58 UTC
CC: @jpbede 

An integration test that removes a CNAME and puts an A record in its place frequently fails.

https://github.com/StackExchange/dnscontrol/runs/2530119113?check_suite_focus=true

```
=== RUN   TestDNSProviders/***/15:TypeChange:Create_a_CNAME
    integration_test.go:200: CREATE CNAME foo.*** google.com. ttl=300
=== RUN   TestDNSProviders/***/15:TypeChange:Change_to_A_record
    integration_test.go:200: CREATE A foo.*** 1.2.3.4 ttl=300
    integration_test.go:204: unexpected status code 422: ***/api/v1/servers/***/zones/*** RRset foo.***. IN A: Conflicts with pre-existing RRset
```

**Comment by jpbede** [comment] 2021-05-07 19:12
Thanks for the heads up. Will check this

**Comment by jpbede** [comment] 2021-05-09 08:14
I've check this. It seems to me to be a weird timing problem.
 
It seems that PowerDNS has accepted the change, replied with a HTTP 200 but the storage engine hasn't done the change yet. Then the next test case gets the records without the prev. created ones. Which then fails, as the prev. record needs to be removed first.

I can't reproduce this running the test locally but when running them on my infra. the tests also fails occasionally.
When i add a `time.Sleep` after a delete or create/update the problem doesn't occur anymore.

I've increased the loglevel on the stage PowerDNS, maybe i can figure out something without adding a `time.Sleep` after delete/update/create.

You're open to disable PowerDNS tests temporarily.

**Comment by tlimoncelli** [comment] 2021-05-10 12:51
Yeah, that test finds bugs with many providers.  Often it is like your situation... a "eventual consistency" database gets confused.   

At least it isn't a situation like with one provider where the code had to change to a different API call, which required refactoring a lot of DNSControl code!

Some ideas:
* If the error is detected, retry a few times before giving up with an error.
* Re-order the changes so that the "delete" happens early, giving enough time for the database to catch up by the time the "add" comes along.
* Talk with PowerDNS to see if they have a suggestion.
* Just do a `time.Sleep()` and be done with it... especially if the sleep only happens when changing CNAMEs to As.

Hope that helps,
Tom

**Comment by jpbede** [comment] 2021-05-10 13:12
Oh i'm damn stupid 🙈  I totally forgotten that Go doesn't keep the sorting of a `map`. Not the first time i forgot this.

I'm sorting the delete corrections in the function `ChangedGroupsDeleteFirst` to the beginning but this doesn't mean that they are kept like this. So it can be likely that the delete may occur after a create correction. 

I'm going to create a fix for this.

**Closed** 2021-05-10 14:18 UTC
Labels: provider-POWERDNS
