### ISSUE TITLE
Feature request: check specific zone

### ISSUE THREAD

**Issue by karlism** [StackExchange/dnscontrol#454] opened 2019-03-05 11:52 UTC
Hello,

I would like to request specific feature - option to check one zone only. Something similar to `dnscontrol preview --domains value` command but for `dnscontrol check`:

```
$ cat dnsconfig.js                         
// Providers:
var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
var DNS_BIND = NewDnsProvider('bind', 'BIND', {
        'default_soa': {
            'master': 'master.example.com.',
            'mbox': 'hostmaster.example.com.',
            'refresh': 3600,
            'retry': 600,
            'expire': 604800,
            'minttl': 1440,
        },
        'default_ns': [
            'ns1.example.com.',
            'ns2.example.com.',
            'ns3.example.com.',
            'ns4.example.com.'
        ]
});

// Domains:
D('example.com', REG_NONE, DnsProvider(DNS_BIND),
    DefaultTTL('30m'),
    NAMESERVER_TTL('1h'),
    A('@', '10.10.10.10'),
    A('localhost', '127.0.0.1')
);
D('example.net', REG_NONE, DnsProvider(DNS_BIND),
    DefaultTTL('30m'),
    NAMESERVER_TTL('1h'),
    A('@', '10.10.10.10'),
    A('localhost', '127.0.0.1'),                 // incorrect duplicate record
    CNAME('localhost', 'localhost.example.com.') // incorrect duplicate record
);
```

Currently it is not possible to check one specific zone for errors, in example above second zone (example.net) contains duplicate DNS records (A and CNAME) for `localhost`. Running check command correctly points out this error:
```
$ dnscontrol check                                                                                                          
1 Validation errors:
ERROR: Cannot have CNAME and A record with same name: localhost.example.net
Exiting due to validation errors
```

I would like to have option to limit check command to specific DNS zone, for example:
```
$ dnscontrol check --domains example.com
```

**Comment by captncraig** [comment] 2019-03-05 16:23
Can I ask why? The point of check is to do a quick syntax check on the whole file, as an easy validation step that doesn't require any provider credentials. It is always going to be fast.

In what situation will you have multiple domains with validation errors at the same time. The whole point of the thing is that you are supposed to keep your repo in a state where it has no errors, and you just want to avoid adding new ones. Unless making huge changes all at once (which I'd discourage), you shouldn't have multiple zones with errors at all.

**Comment by karlism** [comment] 2019-03-06 07:45
My specific case is following - we have a script that generates dnscontrol zone files and checks them before uploading to DNS servers by running `dnscontrol preview --domains example.com` command. Since we're also creating reverse DNS records automatically, changes are usually in multiple zones simultaneously. Each zone is also stored in multiple separate zone files:
```
require("zones/example_com-dynamic.js")
require("zones/example_com-static.js")
require("zones/example_net-dynamic.js")
require("zones/examlpe_net-static.js")
require("zones/10_in-addr_arpa-dynamic.js")
require("zones/10_in-addr_arpa-static.js")
```
Now imagine there's an error in `example.net` zone. What happens is following:
1) previous script execution had failed because of broken `example.net` zone
2) script is run again and generates `example.com` zone, this zone is correct, but `dnscontrol preview --domains example.com` fails because of errors in `example.net` zone (since it appears to be internally running `dnscontrol check` command before creating preview)
3) since script execution had failed in previous step, `example.net` is never updated on the server that executes script and all process remains broken until someone manually fixes `example.net` zone

There are two solutions for this - create some kind of workaround in our scripts that do not leave broken dnscontrol zones behind or have `dnscontrol check --domains example.com` check so we can see specifically which DNS zone had failed prior to uploading it to DNS servers.

**Comment by tlimoncelli** [comment] 2019-03-06 13:59
The fundamental problem is that `dnscontrol check` does many things: some are specific to a domain, others are cross-domain.  Separating them out is difficult.  It does a syntax check, transformations and generators, and then it does the validations (like the CNAME check you mentioned).

Suppose you have updated DomainA but it is DomainB that has the syntax check.  No amount of editing DomainA is going to fix this problem.

The code I'm talking about is  `pkg/normalize/validate.go`/``NormalizeAndValidateConfig()`

Some possibilities:

* refactor `NormalizeAndValidateConfig` to make it easier to do the global work, but have some checks only apply to a certain domain.  The problem is that if global work fails, you don't know if it is your domain or another.
* refactor `NormalizeAndValidateConfig` to record if an error is a global error or tied to a specific domain. We could add a flag to return result codes that indicate a global error or if one of the `--domains` contains an error.  You'd still have the problem with global errors, but at least you'd know you have the problem.
* add a "checksyntax" command that only checks the syntax. That will get 90% of the global problems and will probably be easiest to implement. (or maybe add a `--syntaxonly` flag to the `check` command, which is similar to the first bullet)

**Comment by tlimoncelli** [comment] 2020-03-10 13:05
This has been open for a year with no new discussion. Closing.  Please re-open if you wish.

**Closed by tlimoncelli** 2020-03-10 13:05 UTC
Labels: wontfix
