### ISSUE TITLE
Idea: DELETE() command for use together with NO_PURGE

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#797] opened 2020-08-01 15:35 UTC
As well-documented [NO_PURGE](https://stackexchange.github.io/dnscontrol/js#NO_PURGE) can't know when a specific DNS record was removed and if it should be deleted on the actual DNS zone as well. In this case it might be handy to allow forcing the deletion of specific DNS records (technically solved like [IGNORE()](stackexchange.github.io/dnscontrol/js#IGNORE) with regex) by having a `DELETE("*.go.away.domain.tld")` function?

So each time dnscontrol is run, it makes sure the provided records are going to be deleted. If they are already gone, it's being ignored without failing. This instruction can then be manually removed during the next change.

(Just want to check if this would fit well into dnscontrol.)

**Comment by tlimoncelli** [comment] 2020-08-03 15:50
I'm not against this but the current code would make this difficult to implement.  This touches some of the most brittle sections of code (especially the diffing algorithm).   NO_PURGE and IGNORE are quick hacks; I wouldn't depend on them heavily.  I'd feel differently if there was a better test harness that gave us confidence that changes in one place didn't break something in other places.

**Comment by patschi** [comment] 2020-08-03 17:28
Just a further thought:
* Using a syntax like `DELETE(TXT('@', 'NO_PURGE works brilliantly well'))` might be even better, IMO.
* If the record exist according to DNS provider: We could add the record object into "existing", but removing it from "desired", which - in theory - should make dnscontrol to interpret it as "to delete".
* If the record does NOT exist according to DNS provider: Ignoring it in "existing" and "desired", so no modification is done.

That way it should work with the existing logic, without breaking something else.

**Comment by patschi** [comment] 2020-09-09 22:26
Sorry for pushing, but is this an acceptable way for you, @tlimoncelli?

**Comment by tlimoncelli** [comment] 2020-09-09 23:50
It is difficult for me to give feedback because normally I judge a proposal based on how well it satisfies a particular use case.  I can't think of a specific use-case where this would be used.  

Could you give me an example problem your site is having that would be remedied by this feature?

**Comment by tlimoncelli** [comment] 2023-05-16 00:53
Good news!  The diff2 algorithm has all the hooks required to implement this. See https://github.com/StackExchange/dnscontrol/issues/2064

I'm not sure if I'll be adding this after diff1 is removed or sooner, but it is now much more possible to add such features.  The old (diff1) code was very complex and difficult to modify.

**Comment by tlimoncelli** [comment] 2023-12-14 20:02
This is a duplicate of https://github.com/StackExchange/dnscontrol/issues/2064. Closing.

**Closed by tlimoncelli** 2023-12-14 20:02 UTC
Labels: Type: Enhancement, Priority: p4 - Lowest
