### ISSUE TITLE
Integration tests failing (TestFormatTypes)

### ISSUE THREAD

**Issue by MaxHorstmann** [StackExchange/dnscontrol#790] opened 2020-07-24 21:47 UTC
Following the instructions in [How to build and ship a release](https://stackexchange.github.io/dnscontrol/release-engineering), **Step 2. Run the integration tests**, I'm getting this output:

```
 # go test ./...

?   	github.com/StackExchange/dnscontrol/v3	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build/generate	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/build/validate	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/cmd/convertzone	[no test files]
--- FAIL: TestFormatTypes (0.10s)
    --- FAIL: TestFormatTypes/simple.com/js (0.01s)
        gz_test.go:24: testFormat mismatch (-got +want):
            -var bind = NewDnsProvider("bind", "BIND");
            -var REG_CHANGEME = NewRegistrar("ThirdParty", "NONE");
            -D("simple.com", REG_CHANGEME,
            -	DnsProvider(bind),
            -	//SOA('@', 'ns3.serverfault.com.', 'sysadmin.stackoverflow.com.', 2020022300, 3600, 600, 604800, 1440),
            -	//NAMESERVER('ns-1313.awsdns-36.org.'),
            -	//NAMESERVER('ns-736.awsdns-28.net.'),
            -	//NAMESERVER('ns-cloud-c1.googledomains.com.'),
            -	//NAMESERVER('ns-cloud-c2.googledomains.com.'),
            -	MX('@', 1, 'aspmx.l.google.com.'),
            -	MX('@', 5, 'alt1.aspmx.l.google.com.'),
            -	MX('@', 5, 'alt2.aspmx.l.google.com.'),
            -	MX('@', 10, 'alt3.aspmx.l.google.com.'),
            -	MX('@', 10, 'alt4.aspmx.l.google.com.'),
            -	TXT('@', 'google-site-verification=O54a_pYHGr4EB8iLoGFgX8OTZ1DkP1KWnOLpx0YCazI'),
            -	TXT('@', 'v=spf1 mx include:mktomail.com ~all'),
            -	TXT('m1._domainkey', 'v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCZfEV2C82eJ4OA3Mslz4C6msjYYalg1eUcHeJQ//QM1hOZSvn4qz+hSKGi7jwNDqsZNzM8vCt2+XzdDYL3JddwUEhoDsIsZsJW0qzIVVLLWCg6TLNS3FpVyjc171o94dpoHFekfswWDoEwFQ03Woq2jchYWBrbUf7MMcdEj/EQqwIDAQAB'),
            -	CNAME('dev', 'stackoverflowsandbox2.mktoweb.com.'),
            -	CNAME('dev-email', 'mkto-sj310056.com.'),
            -	TXT('m1._domainkey.dev-email', 'v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIBezZ2Gc+/3PghWk+YOE6T9HdwgUTMTR0Fne2i51MNN9Qs7AqDitVdG/949iDbI2fPNZSnKtOcnlLYwvve9MhMAMI1nZ26ILhgaBJi2BMZQpGFlO4ucuo/Uj4DPZ5Ge/NZHCX0CRhAhR5sRmL2OffNcFXFrymzUuz4KzI/NyUiwIDAQAB'),
            -	CNAME('email', 'mkto-sj280138.com.'),
            -	CNAME('info', 'stackoverflow.mktoweb.com.'),
            -	SRV('_sip._tcp', 10, 60, 5060, 'bigbox.example.com.')
            -)
            +var bind = NewDnsProvider("bind", "BIND");
            +var REG_CHANGEME = NewRegistrar("ThirdParty", "NONE");
            +D("simple.com", REG_CHANGEME,
            +	DnsProvider(bind),
            +	//SOA('@', 'ns3.serverfault.com.', 'sysadmin.stackoverflow.com.', 2020022300, 3600, 600, 604800, 1440),
            +	//NAMESERVER('ns-1313.awsdns-36.org.'),
            +	//NAMESERVER('ns-736.awsdns-28.net.'),
            +	//NAMESERVER('ns-cloud-c1.googledomains.com.'),
            +	//NAMESERVER('ns-cloud-c2.googledomains.com.'),
            +	MX('@', 1, 'aspmx.l.google.com.'),
            +	MX('@', 5, 'alt1.aspmx.l.google.com.'),
            +	MX('@', 5, 'alt2.aspmx.l.google.com.'),
            +	MX('@', 10, 'alt3.aspmx.l.google.com.'),
            +	MX('@', 10, 'alt4.aspmx.l.google.com.'),
            +	TXT('@', 'google-site-verification=O54a_pYHGr4EB8iLoGFgX8OTZ1DkP1KWnOLpx0YCazI'),
            +	TXT('@', 'v=spf1 mx include:mktomail.com ~all'),
            +	TXT('m1._domainkey', 'v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCZfEV2C82eJ4OA3Mslz4C6msjYYalg1eUcHeJQ//QM1hOZSvn4qz+hSKGi7jwNDqsZNzM8vCt2+XzdDYL3JddwUEhoDsIsZsJW0qzIVVLLWCg6TLNS3FpVyjc171o94dpoHFekfswWDoEwFQ03Woq2jchYWBrbUf7MMcdEj/EQqwIDAQAB'),
            +	CNAME('dev', 'stackoverflowsandbox2.mktoweb.com.'),
            +	CNAME('dev-email', 'mkto-sj310056.com.'),
            +	TXT('m1._domainkey.dev-email', 'v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIBezZ2Gc+/3PghWk+YOE6T9HdwgUTMTR0Fne2i51MNN9Qs7AqDitVdG/949iDbI2fPNZSnKtOcnlLYwvve9MhMAMI1nZ26ILhgaBJi2BMZQpGFlO4ucuo/Uj4DPZ5Ge/NZHCX0CRhAhR5sRmL2OffNcFXFrymzUuz4KzI/NyUiwIDAQAB'),
            +	CNAME('email', 'mkto-sj280138.com.'),
            +	CNAME('info', 'stackoverflow.mktoweb.com.'),
            +	SRV('_sip._tcp', 10, 60, 5060, 'bigbox.example.com.')
            +)
    --- FAIL: TestFormatTypes/simple.com/tsv (0.01s)
        gz_test.go:25: testFormat mismatch (-got +want):
            -simple.com	@	300	IN	SOA	ns3.serverfault.com. sysadmin.stackoverflow.com. 2020022300 3600 600 604800 1440
            -simple.com	@	172800	IN	NS	ns-1313.awsdns-36.org.
            -simple.com	@	172800	IN	NS	ns-736.awsdns-28.net.
            -simple.com	@	172800	IN	NS	ns-cloud-c1.googledomains.com.
            -simple.com	@	172800	IN	NS	ns-cloud-c2.googledomains.com.
            -simple.com	@	300	IN	MX	1 aspmx.l.google.com.
            -simple.com	@	300	IN	MX	5 alt1.aspmx.l.google.com.
            -simple.com	@	300	IN	MX	5 alt2.aspmx.l.google.com.
            -simple.com	@	300	IN	MX	10 alt3.aspmx.l.google.com.
            -simple.com	@	300	IN	MX	10 alt4.aspmx.l.google.com.
            -simple.com	@	300	IN	TXT	"google-site-verification=O54a_pYHGr4EB8iLoGFgX8OTZ1DkP1KWnOLpx0YCazI"
            -simple.com	@	300	IN	TXT	"v=spf1 mx include:mktomail.com ~all"
            -m1._domainkey.simple.com	m1._domainkey	300	IN	TXT	"v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCZfEV2C82eJ4OA3Mslz4C6msjYYalg1eUcHeJQ//QM1hOZSvn4qz+hSKGi7jwNDqsZNzM8vCt2+XzdDYL3JddwUEhoDsIsZsJW0qzIVVLLWCg6TLNS3FpVyjc171o94dpoHFekfswWDoEwFQ03Woq2jchYWBrbUf7MMcdEj/EQqwIDAQAB"
            -dev.simple.com	dev	300	IN	CNAME	stackoverflowsandbox2.mktoweb.com.
            -dev-email.simple.com	dev-email	300	IN	CNAME	mkto-sj310056.com.
            -m1._domainkey.dev-email.simple.com	m1._domainkey.dev-email	300	IN	TXT	"v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIBezZ2Gc+/3PghWk+YOE6T9HdwgUTMTR0Fne2i51MNN9Qs7AqDitVdG/949iDbI2fPNZSnKtOcnlLYwvve9MhMAMI1nZ26ILhgaBJi2BMZQpGFlO4ucuo/Uj4DPZ5Ge/NZHCX0CRhAhR5sRmL2OffNcFXFrymzUuz4KzI/NyUiwIDAQAB"
            -email.simple.com	email	300	IN	CNAME	mkto-sj280138.com.
            -info.simple.com	info	300	IN	CNAME	stackoverflow.mktoweb.com.
            -_sip._tcp.simple.com	_sip._tcp	300	IN	SRV	10 60 5060 bigbox.example.com.
            +simple.com	@	300	IN	SOA	ns3.serverfault.com. sysadmin.stackoverflow.com. 2020022300 3600 600 604800 1440
            +simple.com	@	172800	IN	NS	ns-1313.awsdns-36.org.
            +simple.com	@	172800	IN	NS	ns-736.awsdns-28.net.
            +simple.com	@	172800	IN	NS	ns-cloud-c1.googledomains.com.
            +simple.com	@	172800	IN	NS	ns-cloud-c2.googledomains.com.
            +simple.com	@	300	IN	MX	1 aspmx.l.google.com.
            +simple.com	@	300	IN	MX	5 alt1.aspmx.l.google.com.
            +simple.com	@	300	IN	MX	5 alt2.aspmx.l.google.com.
            +simple.com	@	300	IN	MX	10 alt3.aspmx.l.google.com.
            +simple.com	@	300	IN	MX	10 alt4.aspmx.l.google.com.
            +simple.com	@	300	IN	TXT	"google-site-verification=O54a_pYHGr4EB8iLoGFgX8OTZ1DkP1KWnOLpx0YCazI"
            +simple.com	@	300	IN	TXT	"v=spf1 mx include:mktomail.com ~all"
            +m1._domainkey.simple.com	m1._domainkey	300	IN	TXT	"v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCZfEV2C82eJ4OA3Mslz4C6msjYYalg1eUcHeJQ//QM1hOZSvn4qz+hSKGi7jwNDqsZNzM8vCt2+XzdDYL3JddwUEhoDsIsZsJW0qzIVVLLWCg6TLNS3FpVyjc171o94dpoHFekfswWDoEwFQ03Woq2jchYWBrbUf7MMcdEj/EQqwIDAQAB"
            +dev.simple.com	dev	300	IN	CNAME	stackoverflowsandbox2.mktoweb.com.
            +dev-email.simple.com	dev-email	300	IN	CNAME	mkto-sj310056.com.
            +m1._domainkey.dev-email.simple.com	m1._domainkey.dev-email	300	IN	TXT	"v=DKIM1;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCIBezZ2Gc+/3PghWk+YOE6T9HdwgUTMTR0Fne2i51MNN9Qs7AqDitVdG/949iDbI2fPNZSnKtOcnlLYwvve9MhMAMI1nZ26ILhgaBJi2BMZQpGFlO4ucuo/Uj4DPZ5Ge/NZHCX0CRhAhR5sRmL2OffNcFXFrymzUuz4KzI/NyUiwIDAQAB"
            +email.simple.com	email	300	IN	CNAME	mkto-sj280138.com.
            +info.simple.com	info	300	IN	CNAME	stackoverflow.mktoweb.com.
            +_sip._tcp.simple.com	_sip._tcp	300	IN	SRV	10 60 5060 bigbox.example.com.
    --- FAIL: TestFormatTypes/simple.com/zone (0.00s)
        gz_test.go:26: testFormat mismatch (-got +want):
            -$ORIGIN simple.com.
            -$TTL 300
...     <2400 lines in total>
FAIL
FAIL	github.com/StackExchange/dnscontrol/v3/providers/octodns/octoyaml	0.162s
?   	github.com/StackExchange/dnscontrol/v3/providers/opensrs	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/ovh	[no test files]
?   	github.com/StackExchange/dnscontrol/v3/providers/powerdns	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/route53	(cached)
?   	github.com/StackExchange/dnscontrol/v3/providers/softlayer	[no test files]
ok  	github.com/StackExchange/dnscontrol/v3/providers/vultr	(cached)
FAIL
```

Any idea why the tests appear to be failing?

Also, bonus question: I ran this inside of a `golang:1.14-alpine` container (just like the [Dockerfile](https://github.com/StackExchange/dnscontrol/blob/master/Dockerfile#L1)), and the tests at first complained that...

```
exec: "gcc": executable file not found in $PATH
```

Running `apk add build-base` fixed this. Why do the integration tests require `gcc`?

**Comment by tlimoncelli** [comment] 2020-07-25 15:05
= gcc:

I have no idea why that would be required.  I use the standard Go package, not the "cgo" package (it requires GCC because it lets you link to C code.  Maybe it just requires build-base just in case you want to use cgo?  No idea.

== the failing test:

No clue.  I can't reproduce this with centos or macos.  I'm at ea328263c746747b205569d0a0ffadbc19447afd

The fact that all 3 tests are failing makes me think it is a problem with the surrounding infrastructure, not the test.  The fact that the "got/wanted" diff is claiming each line is different, when they're really the same, is curious.

Are you at the master head?

**Comment by tlimoncelli** [comment] 2020-07-25 15:17
Is it possible that the diff's are so long because one file has unix line endings and the other has windows line endings?

Just fyi... the last time all 3 of those tests failed at the same time was due to a problem with the tests, not the tests themselves.  You can see the tests all fail on 44bd4206e82a3521ce6f91bf7002bc96f1fcc3cb but all work on the next commit 5f66991458134b360da6a77282bacba740f974c2

**Comment by tlimoncelli** [comment] 2020-09-04 21:11
I'm closing this. We'll be on the look-out for this problem when we move to Github Actions.

**Closed by tlimoncelli** 2020-09-04 21:11 UTC
Labels: bug
