### ISSUE TITLE
Route53 get-zones/preview/push doesn't handle trailing dots consistently

### ISSUE THREAD

**Issue by truthdoug** [StackExchange/dnscontrol#719] opened 2020-04-16 16:13 UTC
I'm spinning up dnscontrol for existing domains. I used `get-zones` to get records from one of my domains like this:

    dnscontrol get-zones -format=js  r53_creds ROUTE53 mydomain.com

The CNAMES look like this:

    CNAME('www.truthdoug-test', 'test-web.mydomain.com')

If I past the records into dnsconfig.js and run preview, I get a lot of errors for these CNAMEs:

    ERROR: In CNAME www.doug-test.mydomain.com: target (test-web.mydomain.com) must end with a (.) [https://stackexchange.github.io/dnscontrol/why-the-dot]

I get similar errors for MX records.

I can and will edit the js to get this to work but is there an option to `get-zones` that I'm missing? 

(I'm using dnscontrol 3.0.0 installed on mac using homebrew)

**Comment by tlimoncelli** [comment] 2020-04-16 16:24
`get-zones` is pretty new and it looks like you definitely found a bug.  Please edit those manually and I'll check into that this weekend.

Thank you for filing the bug!  I might never have noticed that!

**Comment by truthdoug** [comment] 2020-04-16 17:17
You're welcome. I'm brand new to dnscontrol and loving it. It's going to make my life much better. `get-zones` is a blessing for migrations.

I found another bug which I'll file separately for route53 aliases.

**Comment by truthdoug** [comment] 2020-04-16 17:27
More data... after I edited the js to add the dots for the targets and run `preview`, shows all of these CNAMEs being changed:

    MODIFY CNAME www.truthdoug-test.mydomain.com: (test-web.mydomain.com ttl=300) -> (test-web.mydomain.com. ttl=300)

**Comment by tlimoncelli** [comment] 2020-04-16 22:07
Interesting!  I can't reproduce the error.  

```
$ dnscontrol get-zones -format=js r53 ROUTE53 sstatic.net |grep CNAME
	CNAME('www', 'sstatic.net.', TTL(300))
```

can you try building from master?

**Comment by truthdoug** [comment] 2020-04-20 15:18
Interesting indeed. I tested on some other domains and it worked. 

In my initial example, I anonymized the domain name (as you probably guessed). The real domain I had problems with is on the `.xyz` TLD (again anonymizing but I'll use `foo.xyz`). When I test again, this problem still exists but it seems to work fine for domains on `.com` and `.org`.

It's very consistent for the `foo.xyz` domain. For that domain, I have `CNAMES` going to other subdomains on `foo.xyz` but also to hosts on `amazonaws.com` and `herokudns.com` and those are missing the trailing dot as well.

One other possibly relevant fact for my domain is that it has ~300 records and ~260 of those are `CNAME` records.

**Comment by tlimoncelli** [comment] 2020-04-20 16:18
Quite odd!

At this point, I'm kind of grasping at straws.

1.  Try different formats.  Does the problem go away with -format=tsv or =zone?

2. Is there a chance that the CNAMEs in the .xyz domain are missing the trailing "."?

Try comparing the output of `dig +short` for some .com and some .xyz examples.  Include a trailing dot on the command line, and see if CNAME has a trailing dot.

```
$ dig +short mail.whatexit.org. cname
ghs.googlehosted.com.
```

3. If neither of those work...

I've made a version that outputs extra debugging information: https://github.com/StackExchange/dnscontrol/pull/722

If you can run it, and share the output with me (tal at whatexit dot org) that would be great. Of course, please do not violate any privacy or security policies by sharing that with me.

**Comment by truthdoug** [comment] 2020-04-20 19:09
1. Same results with tsv or zone format.
2. Yes, very good chance. As I tried the new version with much more logging, I see that of the 260+ CNAMES, there are about 5 that have a trailing dot. Most of these 260 records were created using [ansible's route53 module](https://docs.ansible.com/ansible/latest/modules/route53_module.html) but not all. The five that have the trailing dot were not created with ansible but there are many others in a similar situation that are missing the dot. When I log into the AWS console, I see the dots missing when I look at individual records as well.

If I use `dig +short`, they all come back with the trailing dot – even those that show w/o the dot in get-zones output. Seems like dig does some autocorrection.

I'm willing to accept that this is a problem relatively unique to my situation and let you close this issue. If/when others encounter this problem, hopefully they'll find this discussion and can re-open or cite it in a new issue.

(It's not easy for me to anonymize this enough for it to be useful, so I'm not sending the output.)

**Comment by tlimoncelli** [comment] 2020-04-20 19:19
I'm pretty sure dig doesn't do any corrections. It prides itself in being
very raw.  I'm guessing this is some weird interaction with how ansible
creates the records and the .xyz provider. Often providers try to "be
smart" and just add confusion. Before dnscontrol was released to the
outside world I kept trying to make it smart and painted myself into a
corner many times.  Now it is "opinionated" and strict.

That said... yes, I agree we should close this issue.  get-zones's goal is
to create a "good first draft"... which it seems to be doing.

Best,
Tom

**Comment by truthdoug** [comment] 2020-04-20 19:29
It has absolutely reached that goal! Thanks!

**Comment by truthdoug** [comment] 2020-04-21 14:22
Reopening because this is also a problem with preview/push.

I was able to recreate this using a .com domain name. In the AWS console, I created a new hosted zone, dougtest.com. Still in the AWS console, I created a CNAME record "www" pointing to "foo.dougtest.com" (*without the trailing dot*)

Ran `get-zones`:

    $ dnscontrol get-zones --format=js r53_main ROUTE53 dougtest.com
    var r53_main = NewDnsProvider("r53_main", "ROUTE53");
    var REG_CHANGEME = NewRegistrar("ThirdParty", "NONE");
    D("dougtest.com", REG_CHANGEME,
            DnsProvider(r53_main),
            NAMESERVER('ns-270.awsdns-33.com.'),
            NAMESERVER('ns-816.awsdns-38.net.'),
            NAMESERVER('ns-1968.awsdns-54.co.uk.'),
            NAMESERVER('ns-1435.awsdns-51.org.'),
            CNAME('www', 'foo.dougtest.com')
    )

Note: no trailing dot here.

I put this into dnsconfig.js, added the trailing dot on the CNAME record. When I run preview, I get:

    MODIFY CNAME www.dougtest.com: (foo.dougtest.com ttl=300) -> (foo.dougtest.com. ttl=300)

It wants to add the dot. That's a good thing, so I push:

    $  dnscontrol push  --domains dougtest.com
    ******************** Domain: dougtest.com
    ----- Getting nameservers from: r53_main
    ----- DNS Provider: r53_main...1 correction
    #1:
    MODIFY CNAME www.dougtest.com: (foo.dougtest.com ttl=300) -> (foo.dougtest.com. ttl=300)
    
    SUCCESS!
    ----- Registrar: none...0 corrections
    Done. 1 corrections.

*But* then I preview again:

    $ dnscontrol preview --domains dougtest.com
    ******************** Domain: dougtest.com
    ----- Getting nameservers from: r53_main
    ----- DNS Provider: r53_main...1 correction
    #1:
    MODIFY CNAME www.dougtest.com: (foo.dougtest.com ttl=300) -> (foo.dougtest.com. ttl=300)
    
    ----- Registrar: none...0 corrections
    Done. 1 corrections.

If I manually edit the CNAME in the AWS console and run preview again, it's clean:

    $ dnscontrol preview --domains dougtest.com
    ******************** Domain: dougtest.com
    ----- Getting nameservers from: r53_main
    ----- DNS Provider: r53_main...0 corrections
    ----- Registrar: none...0 corrections
    Done. 0 corrections.

**Comment by tlimoncelli** [comment] 2020-04-21 15:24
I haven't been able to reproduce the bug.  I used the same domain you did, though I changed dougtest.com to ninjawanted.com.  No luck.

Is there a chance something else is doing updates at the same time?

Once the preview shows "0 corrections", does it stay that way? What if you then change the CNAME to have a new target, such as `CNAME('www', 'bar.dougtest.com.')` does it work as expected?

**Comment by truthdoug** [comment] 2020-04-21 16:54
I just tested again, but on the latest `master` branch (rather than the version from homebrew). When I push it *does* update the record as expected with the trailing dot. Updating the record in dnsconfig to a new target and pushing it worked fine.

`get-zones` still returns the target without the dot and generates template js code without the dot.

So we're back to `get-zones` producing a "good first draft". Odd that you weren't able to see the bug, but feel free to close if you like.

**Comment by tlimoncelli** [comment] 2020-04-21 17:54
Glad you're back to a stable situation.  The newest `github.com/aws/aws-sdk-go` may have helped.  I'll be sure to upgrade it again before the next release.

**Comment by kotnik** [comment] 2021-07-27 14:18
Sorry for bumping up, but I have the same issue using `dnscontrol v3.11.0 ("6fc3534aa3b74bdb4b7fb7092068abc26e4753e1[dirty]") built 25 Jul 21 16:06 UTC`.

I used `dnscontrol get-zones` to import existing AWS Route53 hosted zone with bunch of records, and I had to manually add a dot to each CNAME/MX that didn't have it. And that's fine.

But every `dnscontrol push` tells me:

```1 correction
#1: 
MODIFY CNAME XXX: (YYY ttl=60) -> (YYY. ttl=60)
....
```

And it doesn't do anything.

**Comment by tlimoncelli** [comment] 2021-07-27 15:42
Hi @kotnik !

I'd be glad to help.   I tried to repro your situation and couldn't.  Could you help me reproduce the problem in my environment?

Here's what I did:

1.  I added these records to a domain that is on Route53:

```
    MX("test1", 1000, "stackoverflowsolutions.com."),
    MX("test2", 1000, "foo.stackoverflowsolutions.com."),
    MX("test3", 1000, "info"),
    MX("test4", 1000, "foo.bar.com."),
    CNAME("cnametest1", "stackoverflowsolutions.com."),
    CNAME("cnametest2", "foo.stackoverflowsolutions.com."),
    CNAME("cnametest3", "info"),
    CNAME("cnametest4", "foo.bar.com."),
```

I pushed these into the domain with `dnscontrol preview --domains stackoverflowsolutions.com` then `dnscontrol push --domains stackoverflowsolutions.com`

2. I downloaded these new records

```
$ dnscontrol get-zone --format js  "r53" "ROUTE53" stackoverflowsolutions.com | grep test
	CNAME('cnametest1', 'stackoverflowsolutions.com.'),
	CNAME('cnametest2', 'foo.stackoverflowsolutions.com.'),
	CNAME('cnametest3', 'info.stackoverflowsolutions.com.'),
	CNAME('cnametest4', 'foo.bar.com.'),
	MX('test1', 1000, 'stackoverflowsolutions.com.'),
	MX('test2', 1000, 'foo.stackoverflowsolutions.com.'),
	MX('test3', 1000, 'info.stackoverflowsolutions.com.'),
	MX('test4', 1000, 'foo.bar.com.'),
```

Those look ok to me.   It turned some short names into FQDNs, which is fine. I don't see the problem with missing dots that you had.


3. I used the new data:

I removed my `CNAME()/MX()` statements and inserted the ones that were downloaded in step 2.

Doing a "preview" didn't show any changes:

```
$ dnscontrol preview --domains stackoverflowsolutions.com
INFO: PowerShell not available. Disabling Active Directory provider.
******************** Domain: stackoverflowsolutions.com
----- Getting nameservers from: gcloud
----- Getting nameservers from: r53
----- DNS Provider: gcloud...
0 corrections
----- DNS Provider: r53...
0 corrections
----- Registrar: namedotcom_main...
0 corrections
Done. 0 corrections.
```

I suspect the problem may be the "." that you added.  That is only needed for a FQDN.  In your example, "." wouldn't be needed for `YYY` since that is a shortname.

Either way... hopefully my examples above help you.  If not, please help me reproduce the bug and I'd be glad to do more research. I do want the `get-zone` command to be high-fidelity and any issue like missing dots is a bug I'd like to fix.

Best,
Tom

**Comment by kotnik** [comment] 2021-07-28 14:09
Hello Tom.

I decided to try to replicate this too, so I create an empty zone in AWS Route53 and test it myself too. Here's the whole repo I used for testing: https://github.com/kotnik/testdomain.com

In short, you were right, changes are applied, but one by one! Take a look at the end of my [shell history](https://github.com/kotnik/testdomain.com/blob/master/history.sh). Since the DNS zone I originally had issues is rather big, that means I would have to re-run `dnscontrol push` thousands of times, and also it beats the purpose since CI wouldn't be able to push more than one change.

So now my question is: can `dnscontrol push` change more than one record?

**Comment by kotnik** [comment] 2021-08-02 09:25
Found out that the issue is already documented: https://github.com/StackExchange/dnscontrol/pull/901/files

**Comment by kotnik** [comment] 2021-08-02 09:25
I found out this issue is already documented: https://github.com/StackExchange/dnscontrol/pull/901

**Comment by Subramanian-ERS** [comment] 2022-02-22 17:01
Hello, I am having the same issue with the `get-zone` command while getting the zone records from Route53. It is working perfectly for hosted zone A, but fails to add a trailing dot while getting the zone records for hosted zone B. I cannot find any difference for which this could occur only with specific hosted zones.

I am using the latest release version of v3.14.0.

**Comment by Subramanian-ERS** [comment] 2022-02-23 05:23
Hi @tlimoncelli, so I have around 200 records in an existing R53 zone without a trailing dot. So, that means I have to run dnscontrol push 200 times for all the records to have a trailing dot in the end?

Also, is there no workaround for DNSControl to skip the error that currently occurs if we do not add a trailing dot in the end of such records?

**Comment by tlimoncelli** [comment] 2022-03-14 15:41
In https://github.com/StackExchange/dnscontrol/pull/1418 I made related changes.

**Comment by Subramanian-ERS** [comment] 2022-03-14 15:46
So, I would not have to push 200 times?

**Comment by Subramanian-ERS** [comment] 2022-03-14 15:48
That is amazing. Thank you @tlimoncelli.

**Comment by tlimoncelli** [comment] 2022-03-14 15:55
Glad to help!

Funny story: I didn't think I was able to fix it!  When I fixed the get-zones problem I saw a solution to the other problem!  Sometimes trying is half the battle!

**Comment by tlimoncelli** [comment] 2022-05-09 02:59
Fixed!

**Closed by tlimoncelli** 2022-05-09 02:59 UTC
