### ISSUE TITLE
Missing Header error 400 with OVH on Windows

### ISSUE THREAD

**Issue by Jean-Max** [StackExchange/dnscontrol#392] opened 2018-08-16 18:24 UTC
Running `.\dnscontrol.exe  preview --config zones\zone-file.js` on Windows 10 (from Powershell or Git Bash), gives the following issue:
```
******************** Domain: example.org
----- Getting nameservers from: ovh
Unexpected HTTP return code (400 Bad Request : {"errorCode":"MISSING_HEADER","httpCode":"400 Bad Request","message":"Missing X-Ovh-Consumer header"}).
```

The zone file looks like this:
```
var REG_OVH = NewRegistrar("ovh", "OVH");
var REG_NONE = NewRegistrar('none', 'NONE');
var OVH = NewDnsProvider("ovh", "OVH");

D("example.org", REG_NONE, DnsProvider(OVH),

   // ... many Records are here...

   {'ns_ttl': '3600'}
);
```

Hope you can fix the issue!

Best

**Comment by tlimoncelli** [comment] 2018-08-16 20:00
CC: @masterzen

**Comment by masterzen** [comment] 2018-08-16 21:55
@Jean-Max , I can be wrong, but I think you haven't configured properly the `consumer-key` in your `creds.json`. 

Please see the documentation to obtain this key (as this can be challenging):

https://stackexchange.github.io/dnscontrol/providers/ovh

Let me know if you happen to have the correct key and it's still erroring.

**Comment by redochka** [comment] 2019-01-31 14:56
Hello,
Same issue started happening to me just after i update dnscontrol by running the following command: 

```
    go get -u github.com/StackExchange/dnscontrol
```
Before I update to latest dnscontrol it was working perfectly fine.

This seems to be regression.

**Comment by masterzen** [comment] 2019-01-31 15:13
@redochka 

What version were your running before?
Do you have more information about the error, including the whole text?

**Comment by redochka** [comment] 2019-01-31 19:37
@masterzen sorry for the disturbance it was my fault. 
I wrote:
```
var PROVIDER_OVH = NewDnsProvider("myOvhProvider", "OVH", commonDnsProviderConfig);
```

instead of 

```
var PROVIDER_OVH = NewDnsProvider("ovh", "OVH", commonDnsProviderConfig);
```

The OP @Jean-Max may workaround his problem by replacing:

```
D("example.org", REG_NONE, DnsProvider(OVH),
```

By

```
D("example.org", REG_OVH, DnsProvider(OVH),
```
Since OVH doesn’t allow to host DNS for a domain that is not registered in their registrar. (dual providers scenario not possible) as described at the end of this page: https://stackexchange.github.io/dnscontrol/providers/ovh

**Comment by tlimoncelli** [comment] 2020-01-28 16:21
Can we close this issue?

**Comment by masterzen** [comment] 2020-01-28 16:56
Yes, it seems so.

**Closed** 2020-01-28 17:09 UTC

**Comment by Jean-Max** [comment] 2020-01-29 09:15
Hi @masterzen and @tlimoncelli thanks for your help on this issue!
