### ISSUE TITLE
INWX: several unconvertible type errors

### ISSUE THREAD

**Issue by wararjey** [StackExchange/dnscontrol#2550] opened 2023-09-06 17:00 UTC
**Describe the bug**
Doing a dnscontrol preview or dnscontrol push, dnscontrol prints out several errors for each domain:

```
******************** Domain: example.com
ERROR: ERROR: 27 error(s) decoding:

* 'domain[0].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[10].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[11].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[11].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[12].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[13].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[13].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[14].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[15].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[15].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[16].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[17].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[18].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[18].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[19].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[1].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[1].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[2].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[3].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[3].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[4].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[5].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[6].noDelegation' expected type 'int', got unconvertible type 'bool', value: 'false'
* 'domain[6].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[7].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[8].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
* 'domain[9].transferLock' expected type 'int', got unconvertible type 'bool', value: 'true'
```

I am getting this error message for each domain.

When doing a push, the error messages look similar, and push seems to fails because of those errors.

**To Reproduce**
run dnscontrol preview or push for INWX domains.

**Expected behavior**
I guess dnscontrol should know how to handle the attributes, which it complained about, correctly.

**DNS Provider**
 - INWX

**Additional context**
I have more than 20 domains at inwx, thus the bug reported for inwx backend not being able to handle more than 20 domains might play into this, as well.

Thx & Regards,

**Comment by gvangool** [comment] 2023-09-07 20:29
I submitted that today upstream (https://github.com/nrdcg/goinwx/issues/7) and it got fixed in the https://github.com/nrdcg/goinwx/releases/tag/v0.8.3 release

**Comment by tlimoncelli** [comment] 2023-09-17 14:23
CC @patschi

It looks like we're importing v0.8.3 in the latest release (v4.4.1):

```
$ grep -i inw go.mod
	github.com/nrdcg/goinwx v0.8.3
```

Can you download dnscontrol v4.4.1 and confirm that this issue is resolved?

**Comment by gvangool** [comment] 2023-09-17 20:12
I can confirm that it's resolved on my INWX domains.

**Comment by tlimoncelli** [comment] 2023-09-20 14:56
@gvangool great!  Thanks for checking!

**Closed by tlimoncelli** 2023-09-20 14:56 UTC
