### ISSUE TITLE
Ignore SSHFP record on unsupported providers

### ISSUE THREAD

**Issue by JoyceBabu** [StackExchange/dnscontrol#2572] opened 2023-09-30 08:39 UTC
**Is your feature request related to a problem? Please describe.**
Route53 does not support SSHFP record type. 

**Describe the solution you'd like**
It could be nice to have a way to ignore the error. Can you either
- Ignore the error with a warning similar to how NS records are ignored on CloudFlare
- Add an option to ignore the records for a single DnsProvider

**Describe alternatives you've considered**
I am currently managing the records manually, after IGNORE-ing them in my config file.

**Additional context**

**Comment by tlimoncelli** [comment] 2023-12-14 17:52
Closing.  This is a duplicate of https://github.com/StackExchange/dnscontrol/issues/2432

**Closed by tlimoncelli** 2023-12-14 17:52 UTC
