### ISSUE TITLE
`check` should report the filename, and ideally line, containing the error

### ISSUE THREAD

**Issue by ad8-bdl** [StackExchange/dnscontrol#857] opened 2020-09-16 10:14 UTC
dnscontrol 3.3.0 ("5c0f69ea44dee81100fa4df67d1a558ff224e6f4[dirty]") built 09 Sep 20 23:43 UTC

(docker:latest)

With the `require` and `require_glob` functions, errors in the included file(s) are reported as being in the file that includes the require.
e.g. if `dnsconfig.js` contains only

    require_glob('./subdomains/')

and a file in subdomains/example.com.js includes an error, the `check` command currently reports:

    executing javascript in dnsconfig.js: Error: ReferenceError: 'x' is not defined

It would be nice if it reported something like "executing javascript in example.com.js: Error: ReferenceError: 'x' is not defined", or even better "executing javascript in example.com.js line 7: Error: ReferenceError: 'x' is not defined"

**Comment by tlimoncelli** [comment] 2020-09-16 13:29
CC: @patschi

**Comment by patschi** [comment] 2020-09-16 18:07
@tlimoncelli To be precise `require_glob()` is basically a JS-based wrapper around `require()` , which was implemented longer before. So the core thing to address might be `require()`, not specific to my `require_glob()` implementation.

I've stepped through the code while reproducing an intended crash and it seems to throw the exception at this point:
https://github.com/StackExchange/dnscontrol/blob/de308c095245ee9d8585626d7c3c536ad5209c3f/pkg/js/js.go#L113

But as `require()` loads the file into RAM and then executes it on-the-fly via Otto, there's no filename when error is being thrown:
![image](https://user-images.githubusercontent.com/2029878/93375180-b4f0b480-f84f-11ea-97a9-af3fea4bf06c.png)

This's the part where `executing javascript in dnsconfig.js: Error:` comes from:
https://github.com/StackExchange/dnscontrol/blob/8e9aa1488253e3b508620c4e100fd98e84e5bce9/commands/printIR.go#L107

It might be a bit tricky to get the "real" filename, where error is being caused, to display...

**Comment by tlimoncelli** [comment] 2020-09-16 23:24
Sounds like a bug in otto.  Maybe file a bug there? https://github.com/robertkrimen/otto

Sadly that project is looking a bit dead. That's very worrisome.

**Comment by patschi** [comment] 2020-09-19 14:36
> Sounds like a bug in otto. 

I don't think it is. dnscontrol loads the JavaScript into variable `data`:
https://github.com/StackExchange/dnscontrol/blob/de308c095245ee9d8585626d7c3c536ad5209c3f/pkg/js/js.go#L96

And then runs the JavaScript code in the variable:
https://github.com/StackExchange/dnscontrol/blob/de308c095245ee9d8585626d7c3c536ad5209c3f/pkg/js/js.go#L109

So there's technically no filename from where the JavaScript is loaded from... Unsure if it's possible to trick Otto or overwrite the `err` Interface{} to have a filename included...

**Comment by tlimoncelli** [comment] 2020-09-19 18:58
Good point.  I did look into it a little just now.  otto's `Compile()` function can take a filename, which is then used in error messages.

dnscontrol doesn't use `Compile()`, it uses `Run()`, which doesn't take the filename as a parameter.

I'm not sure if it would be better to refactor dnscontrol to use `Compile()` or find a way to inject the filename into the vm.

Interested in exploring a bit and figuring it out?

**Comment by tlimoncelli** [comment] 2020-10-07 20:17
The code at master seems to fix this.  It's not pretty, but it works!

I think we're ready to close this issue.  Please re-open it if I closed it too early.

**Closed by tlimoncelli** 2020-10-07 20:17 UTC
