### ISSUE TITLE
feature request: Gracefully handle unknown rtypes in conjunction with `get-zones` sub-command

### ISSUE THREAD

**Issue by m-ueberall** [StackExchange/dnscontrol#1257] opened 2021-09-14 15:04 UTC
The `get-zones` sub-command should at least get a `--dont-panic` option to "ignore" unimplemented rtypes (if possible, the output should contain a warning/comment in this regard if the selected output format supports this):

```
[2021-09-14T16:50:03+0200] root@desktop01:~/config/dnscontrol# dnscontrol get-zones --format js netcup NETCUP themenzentrisch.de
var netcup = NewDnsProvider("netcup", "NETCUP");
var REG_CHANGEME = NewRegistrar("ThirdParty", "NONE");
D("themenzentrisch.de", REG_CHANGEME,
        panic: ToRR: Unimplemented rtype OPENPGPKEY

goroutine 1 [running]:
github.com/StackExchange/dnscontrol/v3/models.(*RecordConfig).ToRR(0xc0000ab900)
        /home/runner/work/dnscontrol/dnscontrol/models/record.go:399 +0x8b4
github.com/StackExchange/dnscontrol/v3/models.(*RecordConfig).zoneFileQuoted(0x11fb100)
        /home/runner/work/dnscontrol/dnscontrol/models/target.go:81 +0x6b
github.com/StackExchange/dnscontrol/v3/models.(*RecordConfig).GetTargetCombined(0xc0000ab900)
        /home/runner/work/dnscontrol/dnscontrol/models/target.go:68 +0x1fa
github.com/StackExchange/dnscontrol/v3/commands.formatDsl({0x1171e40, 0xc00017e900}, 0xc0000ab900, 0x0)
        /home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:265 +0x45
github.com/StackExchange/dnscontrol/v3/commands.GetZone({{{0x143e86b, 0xa}}, {0x7fff9bf2a0d9, 0x6}, {0x7fff9bf2a0e0, 0x6}, {0xc00011bbb0, 0x1, 0x1}, {0x7fff9bf2a0d6, ...}, ...})
        /home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:226 +0xeee
github.com/StackExchange/dnscontrol/v3/commands.glob..func5.1(0xc000164280)
        /home/runner/work/dnscontrol/dnscontrol/commands/getZones.go:30 +0x245
github.com/urfave/cli/v2.(*Command).Run(0xc0001b3440, 0xc0001640c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x64a
github.com/urfave/cli/v2.(*App).RunContext(0xc0005ca4e0, {0x16d3150, 0xc000136020}, {0xc000130000, 0x7, 0x7})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81e
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/StackExchange/dnscontrol/v3/commands.Run({0xc0000b80c0, 0x1440177})
        /home/runner/work/dnscontrol/dnscontrol/commands/commands.go:65 +0x2a9
main.main()
        /home/runner/work/dnscontrol/dnscontrol/main.go:35 +0x134
[2021-09-14T16:53:12+0200] root@desktop01:~/config/dnscontrol#
```

_(There's hope that missing rtypes like `OPENPGPKEY`, `SMIMEA` will get added eventually, but the forementioned option/changed behaviour should work in the generic case.)_

__EDIT:__ Added complete stack-trace.

**Comment by tlimoncelli** [comment] 2021-09-14 15:38
Please include the complete stack-trace.

Yeah, I could see how this would make adopting DnsControl difficult.  Sadly the way we've implemented DNS RR types makes this a bit difficult. It might be easier to work around it, or just implement those records.

If someone is using get-zones to built their initial dnsconfig.js file, they're going to have to delete those records eventually (since they aren't supported).

**Comment by m-ueberall** [comment] 2021-09-14 16:18
> Please include the complete stack-trace.

Done (obtained from a different run, though.)

> If someone is using get-zones to built their initial dnsconfig.js file, they're going to have to delete those records eventually (since they aren't supported).

Yes, I was hoping for a different option (see issue #1258) in order to use `dnscontrol` without having to implement all missing rtypes first which IMHO requires _much more_ work.

**Comment by tlimoncelli** [comment] 2023-12-14 17:52
Closing.  This is a duplicate of https://github.com/StackExchange/dnscontrol/issues/2432

**Closed by tlimoncelli** 2023-12-14 17:52 UTC
Labels: Type: Enhancement, Priority: p3 - Low
