### ISSUE TITLE
Long TXT fails with OVH

### ISSUE THREAD

**Issue by lukaszczerpak** [StackExchange/dnscontrol#1003] opened 2020-12-23 20:19 UTC
Hi,

The new version throws an error for long txt that AUTOSPLIT is not enabled. After enabling it, another error is thrown "TXT records with multiple strings not supported by ovh". However, long TXT was working fine with OVH, even today after rolling back to the previous version of dnscontrol.

**Comment by tlimoncelli** [comment] 2020-12-26 11:40
CC: @masterzen

Hi there!

I'm sorry that a recent change has broken the OVH provider.  I'm CC:ing the maintainer.

The problem we were trying to solve is that some people would use a very long TXT record, then switch to a provider that didn't support long txt records.  The root cause was that certain providers were not marked as supporting TXTMulti explicitly, but instead were silently splitting up a long TXT record on the back-end.  The solution was to make this more explicit: Always require AUTOSPLIT or manually split TXT strings.

For OVH to work in this new system, you basically just need to enable TXTMulti for the provider, then modify the API to join the strings together and send them at one big chunk so that the old behavior (splitting them on the back-end) kicks in.

**Comment by tlimoncelli** [comment] 2020-12-26 11:53
P.S.  See https://github.com/StackExchange/dnscontrol/issues/996 for a similar issue with deSEC.

**Comment by masterzen** [comment] 2020-12-26 12:18
I'll have a look this week-end or early next week.

**Comment by lukaszczerpak** [comment] 2020-12-26 12:52
Thank you @tlimoncelli and @masterzen !

**Comment by masterzen** [comment] 2020-12-26 20:07
@tlimoncelli, I just added the `TXTMulti` capability to the OVH provider and the integration tests are passing. Is that enough or should I implement anything?

**Comment by tlimoncelli** [comment] 2020-12-27 19:31
That's it!   If the tests pass, you're good.  If someone finds a reason why that isn't sufficient, I add more tests to catch that situation if it happens again.

You aren't the first to find that the change was so small!    Basically this means their API uses a string that is understood by `PopulateFromString()`.

You might want to check to see other records work too.  CAA, PTR, SRV are the most commonly used types.

**Comment by masterzen** [comment] 2020-12-28 19:43
@lukaszczerpak, 

Can you try PR #1008? 
and let us know if that fixes your original issue?
Thanks !

**Comment by lukaszczerpak** [comment] 2020-12-28 20:20
Many thanks for looking into this @masterzen. I just compiled from master branch but unfortunately it didn't seem to work:

PREVIEW:

```
******************** Domain: xxx
----- Getting nameservers from: ovh
----- DNS Provider: ovh...2 corrections
#1: MODIFY TXT k4._domainkey.xxx: ("v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtuA8Uryra5zMppUYIpUvdPPLDYygUMD4gP84fdLyypzMXKx42e8I/1AtK8H5vDccrCUlBkqwT5fTCMZCDHx57XdA5jgaQ5Q6HSO728dOKu2KeOH1kNasmTfycAdXXpD++lnV9tZsFDu9vlqIPvKaeul7nDLgjgR9sOR4zWrL/IDEgsP4aa/30vKeIJd0Zl7odfCchuOevF87P8iyqQ1QNFqpMxKSZD+kc+dBYc52r7v8plE5yvTJQF9VsNtUjFDW0vumIc9QXUdeVz+xYMcFVhpEW9Ca/kzhwyXfD4wIWlT9RzKlrHMG0VHL7tt1beAMPv2aMISESbWKDZThAZ6YewIDAQAB" ttl=86400) -> ("v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtuA8Uryra5zMppUYIpUvdPPLDYygUMD4gP84fdLyypzMXKx42e8I/1AtK8H5vDccrCUlBkqwT5fTCMZCDHx57XdA5jgaQ5Q6HSO728dOKu2KeOH1kNasmTfycAdXXpD++lnV9tZsFDu9vlqIPvKaeul7nDLgjgR9sOR4zWrL/IDEgsP4aa/30vKeIJd0Zl7odfC" "chuOevF87P8iyqQ1QNFqpMxKSZD+kc+dBYc52r7v8plE5yvTJQF9VsNtUjFDW0vumIc9QXUdeVz+xYMcFVhpEW9Ca/kzhwyXfD4wIWlT9RzKlrHMG0VHL7tt1beAMPv2aMISESbWKDZThAZ6YewIDAQAB" ttl=86400)
#2: REFRESH zone xxx
----- Registrar: none...0 corrections
Done. 2 corrections.
```

PUSH:

```
******************** Domain: xxx
----- Getting nameservers from: ovh
----- DNS Provider: ovh...2 corrections
#1: MODIFY TXT k4._domainkey.xxx: ("v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtuA8Uryra5zMppUYIpUvdPPLDYygUMD4gP84fdLyypzMXKx42e8I/1AtK8H5vDccrCUlBkqwT5fTCMZCDHx57XdA5jgaQ5Q6HSO728dOKu2KeOH1kNasmTfycAdXXpD++lnV9tZsFDu9vlqIPvKaeul7nDLgjgR9sOR4zWrL/IDEgsP4aa/30vKeIJd0Zl7odfCchuOevF87P8iyqQ1QNFqpMxKSZD+kc+dBYc52r7v8plE5yvTJQF9VsNtUjFDW0vumIc9QXUdeVz+xYMcFVhpEW9Ca/kzhwyXfD4wIWlT9RzKlrHMG0VHL7tt1beAMPv2aMISESbWKDZThAZ6YewIDAQAB" ttl=86400) -> ("v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtuA8Uryra5zMppUYIpUvdPPLDYygUMD4gP84fdLyypzMXKx42e8I/1AtK8H5vDccrCUlBkqwT5fTCMZCDHx57XdA5jgaQ5Q6HSO728dOKu2KeOH1kNasmTfycAdXXpD++lnV9tZsFDu9vlqIPvKaeul7nDLgjgR9sOR4zWrL/IDEgsP4aa/30vKeIJd0Zl7odfC" "chuOevF87P8iyqQ1QNFqpMxKSZD+kc+dBYc52r7v8plE5yvTJQF9VsNtUjFDW0vumIc9QXUdeVz+xYMcFVhpEW9Ca/kzhwyXfD4wIWlT9RzKlrHMG0VHL7tt1beAMPv2aMISESbWKDZThAZ6YewIDAQAB" ttl=86400)
FAILURE! Error 400: "The public key part of the DKIM field is not encoded as a valid Base64 string, or is too short to be a valid key"
#2: REFRESH zone xxx
SUCCESS!
----- Registrar: none...0 corrections
Done. 2 corrections.
completed with errors
```

Previous version didn't split the value and OVH API apparently was able to handle it somehow:

```
;; ANSWER SECTION:
k4._domainkey.xxx. 86400	IN	TXT	"v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtuA8Uryra5zMppUYIpUvdPPLDYygUMD4gP84fdLyypzMXKx42e8I/1AtK8H5vDccrCUlBkqwT5fTCMZCDHx57XdA5jgaQ5Q6HSO728dOKu2KeOH1kNasmTfycAdXXpD++lnV9tZsFDu9vlqIPvKaeul7nDLgjgR9sOR4zWrL/IDEgsP4aa/30vKeIJd0Zl" "7odfCchuOevF87P8iyqQ1QNFqpMxKSZD+kc+dBYc52r7v8plE5yvTJQF9VsNtUjFDW0vumIc9QXUdeVz+xYMcFVhpEW9Ca/kzhwyXfD4wIWlT9RzKlrHMG0VHL7tt1beAMPv2aMISESbWKDZThAZ6YewIDAQAB"
```

**Comment by lukaszczerpak** [comment] 2020-12-29 07:49
I think OVH doesn't support multistring, or there is no clear indication it does. When I looked at the API spec https://api.ovh.com/console/#/domain/zone/%7BzoneName%7D/record#POST the expected value in `target` is string and there is no additional information if this must be split or can exceed 255 chars. Given, the previous dnscontrol version didn't split and values were exceeding 255 chars, it should be just fine to not split and send the value as it is.
What are your thoughts @masterzen ?

**Comment by masterzen** [comment] 2020-12-29 11:55
Hi @lukaszczerpak,

Bad luck, I tested only regular TXT, SPF and CAA records, and forgot DKIM. OVH does a validation on the DKIM records. I'll work on a fix ASAP.

Thanks for the report!

**Comment by masterzen** [comment] 2020-12-29 16:03
I have a fix but it makes an integration test fail.
@tlimoncelli, the problem is that OVH doesn't really support TXT sub-records (like `"one" "two"`), so I have to join the `TXTStrings` before sending to OVH, and do the reverse when receiving records (like you did for #996). The problem is that when sending a TXT record that is smaller than 255 bytes, it isn't possible to reconstruct `TXTStrings` identically (ie I get "onetwo") and the `Create TXTMulti 2` test fails.
Somehow, I feel OVH should not be declared as supporting multi TXT, but it is able to absorb longer strings than 255 bytes, maybe we should have a different capability for such providers ?

**Comment by lukaszczerpak** [comment] 2020-12-29 18:58
Agree. At the moment dnscontrol accepts only two use cases:
* TXT < 255, no need to split, single string value
* TXT > 255, must be split otherwise throws an error - this option also implies the provider supports MultiTXT

@tlimoncelli I would refactor core of dnscontrol to support third use-case where TXT longer than 255 characters is allowed and supported by the provider. This would remove any inconsistency/confusion @masterzen pointed out.

**Comment by tlimoncelli** [comment] 2020-12-30 12:31
I agree. We need a new capability that means “long txt, but only at
265-byte boundaries”--
Sent from Gmail Mobile

**Comment by tlimoncelli** [comment] 2021-03-07 20:04
A number of changes to the TXT code have been merged to `master`.  I hope that fixed everything.

Please try running the integration tests and let me know if this work.

**Comment by tlimoncelli** [comment] 2022-08-10 13:59
I believe this is complete.  Please re-open if not.

**Closed by tlimoncelli** 2022-08-10 13:59 UTC
Labels: Priority: p3 - Low, Status: Needs volunteer
