### ISSUE TITLE
Draft release notes should note that they're a draft

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1722] opened 2022-08-18 21:35 UTC
The current release process automatically generates draft release notes which are then edited by a human.  The draft version should warn readers that this is a draft.  Something like:

```
NOTE: These notes are a DRAFT and will soon be edited by a human. Don't take them seriously yet.
```

OR... is there a way that the release can be marked as preliminary until a person edits it for realz?

CC: @cdhunt

**Comment by cdhunt** [comment] 2022-08-19 15:31
Duplicate of #1709

**Closed by cdhunt** 2022-08-19 15:31 UTC
