### ISSUE TITLE
NAMESERVER should not ignore TTL

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#176] opened 2017-08-07 14:07 UTC
As noted in https://github.com/StackExchange/dnscontrol/pull/171#issuecomment-320589164, you cannot manually set ttl for a nameserver record. You should be able to.

**Comment by ad8-bdl** [comment] 2019-07-25 06:49
The expected behaviour is embodied in `convertzone` and the [documentation](https://stackexchange.github.io/dnscontrol/js#NAMESERVER).

e.g. `convertzone` produces NAMESERVER entries with a TTL modifier:
```
NAMESERVER('ns1.linode.com.', TTL(86400)),
```

However this raises an error with `dnscontrol`:
```
% dnscontrol preview
Executing javascript in dnsconfig.js: NAMESERVER only accepts one argument for name.
```

Removing the TTL entries seems to be an effective workaround.

**Comment by tlimoncelli** [comment] 2020-03-10 15:59
Are there any Registrars that let you set the TTL? I don't know of any, but I'd be glad to be enlightened!

**Comment by tlimoncelli** [comment] 2020-03-14 17:03
Closing due to age.  Please re-open if needed.

**Closed by tlimoncelli** 2020-03-14 17:03 UTC
Labels: enhancement

**Comment by systemcrash** [comment] 2023-03-09 18:43
Welp, bumped into this one. Registrar treats NS records like any other. 

So when the existing records are pulled in, the diff produced always tries to modify the NS entries in `@`. ☹️ Churn and API calls. 

Anyway, `    {"ns_ttl":"3600"},` saved me.
