### ISSUE TITLE
Default SOA for bind doesn't update

### ISSUE THREAD

**Issue by murarisumit** [StackExchange/dnscontrol#246] opened 2017-10-24 07:28 UTC
Input:

```
// Providers:
var VBOX_BIND = NewDnsProvider('bind', 'BIND', {
        'default_soa': {
        'master': 'ns1.example.tld.',
        'mbox': 'sysadmin.example.tld.',
        'refresh': 3600,
        'retry': 600,
        'expire': 604800,
        'minttl': 1440,
    },
    'default_ns': [
        'ns1.example.tld.',
        'ns2.example.tld.',
        'ns3.example.tld.',
        'ns4.example.tld.'
    ]
})
var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.

D('vboxhome.in', REG_NONE, DnsProvider(VBOX_BIND),
    A('@', '1.2.3.4'),
    A('NS', '1.2.3.4'),
    CNAME('host1', 'host1.')
);
```

Produces:

```
$TTL 300
@                IN SOA   DEFAULT_NOT_SET. DEFAULT_NOT_SET. 2017102406 3600 600 604800 1440
                 IN NS    ns1.example.tld.
                 IN NS    ns2.example.tld.
                 IN NS    ns3.example.tld.
                 IN NS    ns4.example.tld.
                 IN A     1.2.3.4
NS               IN A     1.2.3.4
host1            IN CNAME host1.
```

Default SOA's are not updated. Need help in pointing out the issue !

**Comment by captncraig** [comment] 2017-10-24 13:40
Hmm, I run this exact config and I get the expected output:

```
$TTL 300
@                IN SOA   ns1.example.tld. sysadmin.example.tld. 1 3600 600 604800 1440
                 IN NS    ns1.example.tld.
                 IN NS    ns2.example.tld.
                 IN NS    ns3.example.tld.
                 IN NS    ns4.example.tld.
                 IN A     1.2.3.4
NS               IN A     1.2.3.4
host1            IN CNAME host1.
```

Perhaps you are using an older version of dnscontrol?

**Comment by murarisumit** [comment] 2017-10-25 03:53
Stupid me, downloaded the latest binary and it works now. 

Thanks.

**Comment by murarisumit** [comment] 2017-10-25 05:14
Found this issue, can you please try this. If I've already created the zonefile and If I just update**mbox**, there is no change in zonefile.

And can you help with serial number in bind zone file.

**Comment by tlimoncelli** [comment] 2017-10-25 15:24
I can reproduce this bug.

The diff'ing for SOA records is pretty minimal and hasn't been tested much and could use more work.

**Comment by tlimoncelli** [comment] 2017-11-09 18:23
I looked into this a bit. Here's the problem:

The "default_soa" mechanism only works the first time a zonefile  is created.  Sadly this means that if you want to change anything in the SOA, you need to find some other way to update it. (Exception: The serial number is always updated).  One workaround is to delete the zonefile and  let dnscontrol regenerate it from scratch.

How to fix this:  The default_soa settings should always update the SOA, not just provide defaults the first time.  Sadly the code for this part of the BIND provider is rather convoluted.

**Comment by murarisumit** [comment] 2017-11-10 06:08
>  One workaround is to delete the zonefile and let dnscontrol regenerate it from scratch.

I was doing just that, will try and see if I can fix it up

**Comment by techdad** [comment] 2017-12-13 21:31
Hi, for me I can live with the current overall behaviour: I don't expect things other than the serial to change in a given SOA very often. If there is a need to do so, I think in most cases, deleting the zone file and regenerating is fine with the BIND provider.

I also found that you can just delete the single SOA line manually from the zone file and it'll then get re-added, so that's another work around.

However, for me, the serial is not updating either.

I just did a `go get -u github.com/StackExchange/dnscontrol` earlier today. It did update, as I noticed the command-line options all changed.

However, unfortunately, so far I've only been experimenting with dnscontrol creating different records. I've not noted the serial before. Now is the first time I actually wanted to create a real zone to use. So I can't say if this issue has existed previously. I'll test older releases and update later.

Current version running: `dnscontrol 0.2.4-dev`.

**Comment by techdad** [comment] 2017-12-14 19:39
I can confirm an issue with updating the serial in the BIND provider, that exists in v0.2.4, but not in v0.2.3. I'll log a new issue for this.

**Comment by karlism** [comment] 2019-01-24 12:30
This seems to still be an issue with recent DNSControl versions:
```
$ cat dnsconfig.js  
// Providers:
var REG_NONE = NewRegistrar('none', 'NONE');    // No registrar.
var DNS_BIND = NewDnsProvider('bind', 'BIND', {
        'default_soa': {
            'master': 'master.example.com.',
            'mbox': 'hostmaster.example.com.',
            'refresh': 3600,
            'retry': 600,
            'expire': 604800,
            'minttl': 1440,
        },
        'default_ns': [
            'ns1.example.com.',
            'ns2.example.com.'
        ]
});

// Domains:
D('example.com', REG_NONE, DnsProvider(DNS_BIND),
    DefaultTTL('30m'),
    NAMESERVER_TTL('1h'),
    A('@', '10.10.10.10'),
    A('localhost', '127.0.0.1')
);

$ dnscontrol push                                                                      
INFO: Config file "creds.json" does not exist. Skipping.
******************** Domain: example.com
----- Getting nameservers from: bind
----- DNS Provider: bind...1 correction
#1: GENERATE_ZONEFILE: example.com
 (5 records)

CREATING ZONEFILE: zones/example.com.zone
SUCCESS!
----- Registrar: none...0 corrections
Done. 1 corrections.

$ cat zones/example.com.zone | grep SOA                                                
@          300   IN SOA   master.example.com. hostmaster.example.com. 1 3600 600 604800 1440

$ sed -i 's/hostmaster.example.com/hostmaster.example.net/' dnsconfig.js                                                

$ dnscontrol push                                                         
INFO: Config file "creds.json" does not exist. Skipping.
******************** Domain: example.com
----- Getting nameservers from: bind
----- DNS Provider: bind...0 corrections
----- Registrar: none...0 corrections
Done. 0 corrections.
```

And is there a reason for default serial number that is created for new zones to be `1` instead of `YYYYMMDD00`? It makes [workaround](https://github.com/StackExchange/dnscontrol/issues/246#issuecomment-343245306) suggested by @tlimoncelli almost impossible to use as DNS servers would refuse such zone.

**Comment by tlimoncelli** [comment] 2020-03-10 12:54
The code in master reworks how serial numbers are generated and how SOAs are handled. It still requires modifying the zone file to change (for example) retry time, but I think that is so rare that this is sufficient.

**Comment by tlimoncelli** [comment] 2020-03-14 17:03
Closing due to age.  Please re-open if needed.

**Closed by tlimoncelli** 2020-03-14 17:03 UTC
Labels: bug
