### ISSUE TITLE
HEXONET support for additional fields in create-domains

### ISSUE THREAD

**Issue by liljenstolpe** [StackExchange/dnscontrol#1058] opened 2021-02-25 18:18 UTC
I just tried to use the hexonet provider to create a .us domain.  It failed as I had no way of adding the additional objects to register, specifically x-us-nexus-appprofile and x-us-nexus-category.  

It would be nice to have the ability to encode those in the D statement or in the dnsconfig.js

.us isn't the only domain that requires additional data, btw.

**Comment by tlimoncelli** [comment] 2021-02-25 18:47
CC @papakai

**Comment by papakai** [comment] 2021-03-01 11:31
@tlimoncelli yes, this is often a must especially for certain ccTLDs, or restricted TLDs.
[Here](https://github.com/hexonet/whmcs-ispapi-registrar/blob/master/modules/registrars/ispapi/additionaldomainfields_sample.php) a sample file we use for WHMCS.

Is there a way on how to deal with that in dnscontrol? This shouldn't be something specific to HEXONET - other registrars have also to provide such additional data for specific TLDs, just their fields look probably different.

Thanks! :-)

**Comment by papakai** [comment] 2021-03-01 11:40
I am a bit out of DNSControl knowledge, therefore I checked DSL Syntax [here](https://stackexchange.github.io/dnscontrol/js). Wouldn't that be a topic for `DEFAULTS( modifiers... )`?

This topic is a big one specific to domain registrations and I am not sure if this is really of interest for you guys to better support in core somehow?

**Comment by tlimoncelli** [comment] 2021-03-01 12:01
I'm new to this idea so let me start by asking some questions to bring me up to speed:

1. When is this data needed? When buying a domain initially?

2. Is the scope of this data global, per-registrar, or per-domain?  For example, if it is per-registrar, we could attach it as metadata:

var DSP_SERVERFAULT = NewDnsProvider("bind", "BIND", {
    additionalfields: {
         Name: "Highly Regulated TLD",
         Type: "tickbox",
         Required: true,
   }
});

or on the domain:

D("example.com", REG_FOO, {
    additionalfields: {
         Name: "Highly Regulated TLD",
         Type: "tickbox",
         Required: true,
   }
});

**Comment by papakai** [comment] 2021-03-01 12:32
1. Such data is necessary in different processes of a domain: Registration, Owner Change / Trade, Transfer. So, just the registration part affects DNSControl, I guess. Whenever you register a domain where such data is necessary, you have to pass it together with the registration command
2. The scope of this data is per-TLD. So, in context of .us, you have to provide that data for every .us domain name registration. Therefore I guess, the per-registrar scope makes the most sense. Still, as this affects all providers offering this feature, some parts could also make sense to have a global configuration possibility to ease up the per-registrar scope. Example: if a TLD requires providing the VATID or Identification Number, this is probably something ALL providers have to forward. they just come with a different naming convention of this additional data fields. Sometimes this configuration differs a lot between the providers. These data requirements itself are enforcerd by the registries managing such TLDs and the providers are just forwarding this over their Backend System API. Still, I guess, starting with a per-registrar scope to makes more sense. Later a review in direction of global data configuration could be covered.

**Comment by papakai** [comment] 2021-03-01 12:39
Not my example above pointing out the per-TLD scope explicitely.

**Comment by tlimoncelli** [comment] 2021-03-05 00:17
Dumb question but... Is this needed when purchasing a domain?  create-domains doens't purchase the domain for other providers. Does it for HEXONET?

**Comment by papakai** [comment] 2021-03-05 10:07
Yes, looks like that. One point I already addressed in the past to you guys: "create-domains" sounds like a domain being registered. So is this then just about creating a DNSZone? (I guess yes)

**Comment by tlimoncelli** [comment] 2021-03-05 12:57
Yup.  It's just about creating a DNSZone. 

Yes, "create-dnszones" would be a better name.  I will clarify in the docs.  Maybe I should poll other providers to see what it is called there.

**Comment by papakai** [comment] 2021-03-05 13:04
ok, thanks. I'll dive into review as far as possible to get "create-domains" patched.

**Comment by liljenstolpe** [comment] 2021-03-05 17:55
Awesome - thx!

**Comment by papakai** [comment] 2021-03-08 10:52
Just had an initial check of our code base, looks like I've been partially wrong. "create-domains" cares about creating a DNSZone, not about registering a domain in real. so far so good. I've just forgotten that I rewrote exactly that part in that direction before initial launch - I had a lot trouble to understand "create-domains" correctly.

Creating DNSZones, does not require such additional fields. So, I guess the issue is happening somewhere else, where we use domain-related commands. Sorry for the confusion caused.

This is the case in nameservers.go of our provider module:
* [getNameserversRaw](https://github.com/StackExchange/dnscontrol/blob/fb0bcaac64a782b89e3d23af4b0ce303defd15af/providers/hexonet/nameservers.go#L43)(domain string)
* [updateNameservers](https://github.com/StackExchange/dnscontrol/blob/fb0bcaac64a782b89e3d23af4b0ce303defd15af/providers/cscglobal/api.go#L74)(ns []string, domain string)

So, I'll have to continue the discussion here. Are these methods really thought to deal with a domain? Or are they thought to apply / fetch nameserver data on DNSZone Level? (Just want to ensure we are diving into the right things finally)
Right now StatusDomain and ModifyDomain are of course domain-related commands and ModifyDomain has to be seen as the reason for that additional domain fields issue imho.

Thanks @tlimoncelli !

**Comment by papakai** [comment] 2021-03-08 11:02
@liljenstolpe Can you provide the exact domain name related to that .us issue.

**Comment by KaiSchwarz-cnic** [comment] 2022-06-23 15:16
@tlimoncelli this issue is no longer an enhancement, it is a result of missing post-transfer update. nothing you can improve here within DNSControl. Feel free to close the reported issue, communication stopped here anyways.

**Closed** 2022-08-10 13:57 UTC
Labels: Type: Enhancement, Priority: p3 - Low
