### ISSUE TITLE
Support SRV records

### ISSUE THREAD

**Issue by fbjerggaard** [StackExchange/dnscontrol#56] opened 2017-03-22 09:37 UTC
The title basically says it - dnscontrol should support SRV records

**Comment by captncraig** [comment] 2017-03-22 18:14
Yes, we should. Working on it shortly.

**Comment by captncraig** [comment] 2017-03-23 03:55
Looks like various providers are all over the place on how they want srv records formatted. It will be up to us to come up with an acceptable standardized format, and individual providers will just need to adapt to whatever.

We need to convey the following data:

- service (`_sip`)
- protocol (`_tcp`)
- priority
- weight
- port
- target

That seems like a lot. We could accept service/protocol with or without underscores. Some providers add them automatically, and others dont.

Brainstorming ideas:

`SRV("_sip._tcp", 20, 10, 5050, "foo.com.")`

`SRV("sip", "tcp", 20, 10, 5050, "foo.com.")`

// use default weight
`SRV("_sip._tcp", 20, 5050, "foo.com.")`

//similar to above with weight override (like we do ttls)
`SRV("sip", "tcp", 20, 5050, "foo.com", Weight(10)) `

// fully verbose
`SRV("sip", "tcp", "foo.com.", Priority(20), Port(5050), Weight(10))`

I think I'm leaning toward the second option, but the last one also intrigues me. MY fear is that with 3 numeric fields it will be hard to remember the order, and you'll just have to look it up every time.

**Comment by tlimoncelli** [comment] 2017-03-23 14:43
I prefer the first one:

    SRV("_sip._tcp", 20, 10, 5050, "foo.com.")

The order (label, priority, weight, port, target) reflects the fields in a BIND-like zonefile.  There's no need to split out the parts of the label.  When providers list SRV records they don't split it out. See ([this example](https://support.google.com/a/answer/34143?hl=en) and [this one too](https://support.office.com/en-us/article/Create-DNS-records-at-Google-Domains-for-Office-365-0db29490-2612-48bc-9b77-1862e7a41a8c#bkmk_add_srv).)

**Comment by techdad** [comment] 2017-04-17 12:30
Thanks for working on this. Having SRV records work in some way is a deal-breaker for me to use this.
Just a note that the included `convertzone` tool already deals with existing SRV's in an old existing zone, and spits them out as (for example):

        SRV('_xmpp-client._tcp', '0 5 5222 xmpp.domain.tld.', TTL(14400)),

I'd  rather have one of the examples in the thread above, but, at a minimum, even just parsing this would be workable..

**Comment by rbelnap** [comment] 2017-04-24 13:11
Just adding another log to the fire - I have the same use case as techdad.  And unfortunately, because I'm using namecheap, it is "all or nothing" with regards to record support.  (I can't just leave the SRV records alone, because they are removed on every update).  I'm happy to help contribute to the cause, but I don't want to duplicate efforts.  If there is a WIP branch, let me know.  Thanks!

**Comment by tiernano** [comment] 2017-04-27 14:55
just to throw a spanner, i am looking at using this, and i have SRV records for Office365... I run dnscontrol preview and it wants to delete the srv records (from cloudflare) cause they are not in my config...  is there a way to tell it not to delete existing records, but update or add ones?

**Comment by captncraig** [comment] 2017-04-27 15:16
Umm, we sort of have a mechanism for that. If you do `D("example.com", REG, ..., NO_PURGE)` it **should** avoid deleting. #7 needs to be fixed before it truly works that way though. We can do it in a central place so it is not up to the provider to detect that. I can prioritize that and get it in this afternoon. It is an easy fix.

**Comment by tiernano** [comment] 2017-05-02 12:23
just tried adding NO_PURGE to a cloudflare domain, and it is still sugesting the delete in preview, and it deletes it when pushed too...

**Comment by tlimoncelli** [comment] 2017-05-02 17:35
Oh, I'm sorry that happened. I just remembered this bug (https://github.com/StackExchange/dnscontrol/issues/7) which says that not all providers support the NO_PURGE directive. (originally we added it just for AD).

I guess we need to bump up the priority on the SRV record.

**Comment by tiernano** [comment] 2017-05-02 18:23
It was a test domain, just seeing if there was a difference between the preview and push... nothing actually lost (luckily!).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by captncraig** [comment] 2017-05-03 15:47
the no_purge thing should be fixed globally in #111. Except for providers that need to regenerate an entire zone from scratch.

**Comment by tiernano** [comment] 2017-06-05 19:03
Any news on getting srv working? The no purge option is handy, but if you do want to pruge records, it kind of makes things annoying...

**Comment by tlimoncelli** [comment] 2017-06-05 21:29
Sadly we haven't made any progress on SRV records.

**Comment by tlimoncelli** [comment] 2017-07-09 16:52
I'm struggling with whether to add SRV records or add a general mechanism for all future records.

Here are my thoughts:

https://docs.google.com/document/d/1s5v9eWnJCudTA551xkUf-tJF2iLJHOI23wW-J2TTt74/edit?usp=sharing

**Comment by tlimoncelli** [comment] 2017-07-13 10:41
PR https://github.com/StackExchange/dnscontrol/pull/136 is ready for testing. It doesn't support all providers yet, but I try it out and let me know if it works for you and your favorite providers.

**Comment by tlimoncelli** [comment] 2017-07-19 20:02
PR https://github.com/StackExchange/dnscontrol/pull/136 is merged.  SRV is now supported by BIND, NAMEDOTCOM, ROUTE53.

**Comment by tiernano** [comment] 2017-07-20 16:57
Just downloaded the latest code, and tried using the following records, and its failing:

   SRV("_sipfederationtls._tcp", 1, 1, 5061, "sipfed.online.lync.com."),
    SRV("_sip._tls", 1, 1, 443, "sipdir.online.lync.com."),
 
This is the error code:

Initialized 3 registrars and 3 dns service providers.
******************** Domain: tiernanotoole.ie
----- Getting nameservers from: cloudflare
----- DNS Provider: cloudflare... 3 corrections
#1: MODIFY SRV _sip._tls.tiernanotoole.ie: (0 0 0 1\009443\009sipdir.online.lync.com ttl=1) -> (1 1 443 sipdir.online.lync.com. ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#2: MODIFY SRV _sipfederationtls._tcp.tiernanotoole.ie: (0 0 0 1\0095061\009sipfed.online.lync.com ttl=1) -> (1 1 5061 sipfed.online.lync.com. ttl=1)
FAILURE! [{"code":1004,"error_chain":[{"code":9036,"message":""}],"message":"DNS Validation Error"}]
#3: MODIFY MX tiernanotoole.ie: (1 tiernanotoole-ie.mail.protection.outlook.com. ttl=1) -> (0 tiernanotoole-ie.mail.protection.outlook.com. ttl=1)
SUCCESS!
----- Registrar: none
Done. 3 corrections.

The MX record is also being updated to priority of 0, which may (or may not) be related... and by latest code, i mean "go get github.com/stackexchange/dnscontrol" about 20 min ago...

Thanks.

**Comment by tlimoncelli** [comment] 2017-07-20 19:59
I have some bad news and some good news....

The bad news is that the cloudflare provider doesn't yet support SRV records. It should have error'ed during the validation step.

The good news is that it should be pretty easy to implement.  Would you like to take a stab at creating a PR?

**Comment by tlimoncelli** [comment] 2017-07-20 21:50
Some of this was fixed in 710d14b1a976aeed51071fd346e02e8fa12d835a but we're still seeing this problem in the integration test:

```
        --- FAIL: TestDNSProviders/dnscontroltest-gcloud.com/25:_MX_record (0.80s)
        	integration_test.go:131: CREATE MX dnscontroltest-gcloud.com 0 5\ foo.com. ttl=300
        		
        	integration_test.go:144: Expected 0 corrections on second run, but found 1.
        	integration_test.go:146: #0: MODIFY MX dnscontroltest-gcloud.com: (5 foo.com. ttl=300) -> (0 5\ foo.com. ttl=300)
```

**Comment by tlimoncelli** [comment] 2017-07-20 23:05
The rest of this was fixed in caa71c4031843c73fad06dd152e918497c2dccf6 . MX and SRV records were both affected by this.  They're all fixed now.

CC: @pmoroney @tiernano

**Comment by tiernano** [comment] 2017-07-21 07:15
@tlimoncelli thanks for the MX Fix... Going to chance my arm at the other fix now... looks like for SRV records, the content is tab delimited ( "content": "1\t443\tsipdir.online.lync.com",) and they also have a data record, like below, which is required only for SRV records... So, i need to figure that out... 

            "data": {
                "service": "_sip",
                "proto": "_tls",
                "name": "tiernanotoole.ie",
                "priority": 1,
                "weight": 1,
                "port": 443,
                "target": "sipdir.online.lync.com"
            }

**Comment by kjacobsen** [comment] 2017-07-26 12:11
Hi @tlimoncelli, has the CloudFlare provider been updated to support SRV records yet?

**Comment by tlimoncelli** [comment] 2017-07-26 23:22
@kjacobsen The cloudflare provider doesn't yet support SRV records. @tiernano said he is interested in working on a PR. Maybe you two would be interested in working on a PR together?

**Comment by kjacobsen** [comment] 2017-07-26 23:53
Not sure how helpful I will be as I don't know much Go. I can provide support testing.

**Comment by techdad** [comment] 2017-08-01 07:08
Thank you. I can confirm that for a local "bind" provider, the SRV works! Wonderful.

**Comment by tlimoncelli** [comment] 2017-08-05 15:07
This was a real group effort!  Thanks everyone!

**Closed by tlimoncelli** 2017-08-05 15:07 UTC
Labels: enhancement
