### ISSUE TITLE
BUG: hosting_de SRV TTL change crash

### ISSUE THREAD

**Issue by tmkis2** [StackExchange/dnscontrol#2066] opened 2023-02-12 13:07 UTC
Changing just a TTL for a DNS record results in

FAILURE! [{Code:40010 ContextObject: ContextPath: Text:Record with name 'xxxxx', type 'SRV' and content 'xxxx' is a duplicate. Value:}]

Nothing is changed and preview always displays this as to be changed (TTL)

**Comment by tlimoncelli** [comment] 2023-02-12 18:53
CC: @juliusrickert (owner of the hostingde provider)

**Comment by juliusrickert** [comment] 2023-02-13 10:09
@tmkis2 could you provide a minimal reproducible example, please?

I won't get to fixing this until the end of next week.

**Comment by tlimoncelli** [comment] 2023-02-13 15:39
FYI: In case you need it... here's an example of how to add an integration test that covers this situation: https://github.com/StackExchange/dnscontrol/pull/2067/files

**Comment by tmkis2** [comment] 2023-02-15 07:15
@juliusrickert any existing entry will cause this if you change it to another TTL value like adding , TTL(600) to the end of this entry. If the entry doesn't change anything other than the TTL it will fail.
Just now I have to change the entry in hosting.de web panel or change the entry to some (invalid) value and then back to the right value with new TTL

**Comment by tmkis2** [comment] 2023-02-17 05:09
Okay now I am really sure that after the latest dnscontrol update something major happened with at least the hosting_de provider. Every push forces changed lines to be created first (which results in above error for TXT and CNAME records because they can't be full duplicates) and "works" for A records resulting in TWO a records (one with the old value and the second with the new value). Another run from dnscontrol push results in removing the old A record. So for now to change TXT or CNAME records you have to remove them first, run dnscontrol push and then add them with the new values again and run dnscontrol push again.

**Comment by tlimoncelli** [comment] 2023-02-21 18:57
Hey @Yannik could you take a look?

@juliusrickert 

These are the changes since the last version: (if I got the git command correct... which isn't always true!)

```
$ git log ...v3.25.0 providers/hostingde/
```

**Comment by juliusrickert** [comment] 2023-02-21 22:02
@tmkis2 @tlimoncelli I'll be looking into this this weekend.

**Comment by Yannik** [comment] 2023-02-22 12:32
@tmkis2 
> any existing entry will cause this if you change it to another TTL value like adding , TTL(600) to the end of this entry. If the entry doesn't change anything other than the TTL it will fail.

I'm having trouble reproducing your issue. I tried changing TTLs both on TXT records and CNAMEs, but didn't get any errors. I am using the latest master. Could you post both `dnsconfig.js` snippets and the commands you run to reproduce the problem?

**Comment by Yannik** [comment] 2023-02-22 12:38
I'm not seeing any problems with SRV records either:
```
$ ~/projects/dnscontrol/dnscontrol -v push --domains mydomain.de
requiring: ./shared.js (shared.js)
******************** Domain: mydomain.de
1 correction
#1: 
+ CREATE SRV _sip._tcp.mydomain.de 10 60 5060 bigbox.example.tld. ttl=60
SUCCESS!
Done. 1 corrections.

$  vi dnsconfig.js # modify ttl

$ ~/projects/dnscontrol/dnscontrol -v push --domains mydomain.de
requiring: ./shared.js (shared.js)
******************** Domain: mydomain.de
1 correction
#1: 
± MODIFY SRV _sip._tcp.mydomain.de: (10 60 5060 bigbox.example.tld. ttl=60) -> (10 60 5060 bigbox.example.tld. ttl=300)
SUCCESS!
Done. 1 corrections.
```

**Comment by tmkis2** [comment] 2023-02-22 12:53
That's odd. I can't reproduce it with those domains tested before but here we go for a new one:

1. run without any errors and changes:

result:

```
$ dnscontrol push
[...snipped....]
******************** Domain: intensivtransport-deutschland.de
[...snipped....]
Done. 0 corrections.
```

Changing this in dnsconfig.js:

```
D('intensivtransport-deutschland.de', REG_HOSTINGDE, DnsProvider(DNS_HOSTINGDE)
        , AUTODNSSEC_ON
        , DefaultTTL(600)
        , A('@', '45.86.124.174')
        , CNAME('www', '@')
        , drk_mail
);

```

to

```
D('intensivtransport-deutschland.de', REG_HOSTINGDE, DnsProvider(DNS_HOSTINGDE)
        , AUTODNSSEC_ON
        , DefaultTTL(3600)
        , A('@', '45.86.124.174')
        , CNAME('www', '@')
        , drk_mail
);
```

and running dnscontrol push again:

```
$ dnscontrol push
[...snipped....]
******************** Domain: intensivtransport-deutschland.de
1 correction
#1: 
MODIFY CNAME drk._domainkey.intensivtransport-deutschland.de: (drk._domainkey.drk-rhn.de. ttl=600) -> (drk._domainkey.drk-rhn.de. ttl=3600)
MODIFY CNAME autoconfig.intensivtransport-deutschland.de: (mail.drk-rhn.de. ttl=600) -> (mail.drk-rhn.de. ttl=3600)
MODIFY TXT _dmarc.intensivtransport-deutschland.de: ("v=DMARC1; p=none; sp=none; pct=100" ttl=600) -> ("v=DMARC1; p=none; sp=none; pct=100" ttl=3600)
MODIFY SRV _autodiscover._tcp.intensivtransport-deutschland.de: (0 0 443 mail.drk-rhn.de. ttl=600) -> (0 0 443 mail.drk-rhn.de. ttl=3600)
MODIFY TXT _spf1.intensivtransport-deutschland.de: ("v=spf1 ip6:2a0c:8900:2:1041:1:feed:dead:beef ip6:2a0c:8900:1::4db:8bb9 ip6:2a01:4f8:1c17:7e52::1 include:outbound.mailhop.org include:spf.mailjet.com ~all" ttl=600) -> ("v=spf1 ip6:2a0c:8900:2:1041:1:feed:dead:beef ip6:2a0c:8900:1::4db:8bb9 ip6:2a01:4f8:1c17:7e52::1 include:outbound.mailhop.org include:spf.mailjet.com ~all" ttl=3600)
MODIFY TXT _rawspf.intensivtransport-deutschland.de: ("v=spf1 include:spf4.tmkis.com include:spf6.tmkis.com include:outbound.mailhop.org include:spf.mailjet.com ~all" ttl=600) -> ("v=spf1 include:spf4.tmkis.com include:spf6.tmkis.com include:outbound.mailhop.org include:spf.mailjet.com ~all" ttl=3600)
MODIFY CNAME autodiscover.intensivtransport-deutschland.de: (mail.drk-rhn.de. ttl=600) -> (mail.drk-rhn.de. ttl=3600)
MODIFY A intensivtransport-deutschland.de: (45.86.124.174 ttl=600) -> (45.86.124.174 ttl=3600)
MODIFY CNAME smtp.intensivtransport-deutschland.de: (mail.drk-rhn.de. ttl=600) -> (mail.drk-rhn.de. ttl=3600)
MODIFY CNAME imap.intensivtransport-deutschland.de: (mail.drk-rhn.de. ttl=600) -> (mail.drk-rhn.de. ttl=3600)
MODIFY CNAME www.intensivtransport-deutschland.de: (intensivtransport-deutschland.de. ttl=600) -> (intensivtransport-deutschland.de. ttl=3600)
MODIFY TXT intensivtransport-deutschland.de: ("v=spf1 ip4:62.216.179.222 ip4:116.203.86.28 ip4:138.201.156.196 ip4:5.180.192.196 ip4:5.75.244.244 ip6:2001:1a50:100:1::25 ip6:2a01:4f8:c2c:25d9::2 include:_spf1.intensivtransport-deutschland.de ~all" ttl=600) -> ("v=spf1 ip4:62.216.179.222 ip4:116.203.86.28 ip4:138.201.156.196 ip4:5.180.192.196 ip4:5.75.244.244 ip6:2001:1a50:100:1::25 ip6:2a01:4f8:c2c:25d9::2 include:_spf1.intensivtransport-deutschland.de ~all" ttl=3600)
MODIFY MX intensivtransport-deutschland.de: (10 mail.drk-rhn.de. ttl=600) -> (10 mail.drk-rhn.de. ttl=3600)
FAILURE! [{Code:40010 ContextObject: ContextPath: Text:Record with name 'intensivtransport-deutschland.de', type 'MX' and content 'mail.drk-rhn.de' is a duplicate. Value:}]
[...snipped....]
Done. 1 corrections.
completed with errors
```

**Comment by Yannik** [comment] 2023-02-22 13:07
@tmkis2 @tlimoncelli 
I was able to reproduce this with another domain, and traced the problem to the diff function:

The `_, create, del, mod, err = diff.New(dc).IncrementalDiff(records)` call for a TTL change 300->600 results in the following `mod` Changeset:

![Screenshot from 2023-02-22 14-01-57](https://user-images.githubusercontent.com/801996/220627387-e2dffaa1-faf7-47d8-af7c-d4d738cba0ce.png)

As you can see, an incorrect `Original` record is associated with the `Existing` part of the modification entry.  
Therefore, the `ID` of the wrong record is used for the modification API call, resulting in this duplicate record error.

**Comment by tlimoncelli** [comment] 2023-02-22 14:38
`.Original` is set in providers/hostingde/types.go around line 154.

I'm not sure how it could be set wrong sometimes and right other times.  Maybe this is one of those situations where we point to a thing and that thing changes.  Usually we fix that by copying to the local heap (`foo := foo` or `bar := *foo`)

FYI: The `diff2` system has a bug related to TTL changes.   https://github.com/StackExchange/dnscontrol/issues/2088  I don't think it is related.  I hope to fix that bug in the next week.

**Comment by Yannik** [comment] 2023-02-22 18:40
Thanks, @tlimoncelli. You are completely right. I wasn't aware that `Original` was already being set on the records model, prior to the diff call! (That still seems kind of unintuitive to me)

In `ApiRecordsToStandardRecordsModel`, we have this iteration:

```
    for _, r := range src {
        if r.Type == "SOA" {
            continue
        }
        records = append(records, r.nativeToRecord(domain))
    }
```

Then, in `nativeToRecord`, `Original` is set like this:

```
func (r *record) nativeToRecord(domain string) *models.RecordConfig {
...
    rc := &models.RecordConfig{
        Type:         "",
        TTL:          r.TTL,
        MxPreference: r.Priority,
        SrvPriority:  r.Priority,
        Original:     r,
    }
```

As a result, the pointer r is continously overwritten by the range function. Due to this, Original points to the same original  for all records. As this original is the last modified record, it often works without a problem, i.e. for the new records I tested this problem with.

To fix this, I'd simply change this from pass-by-reference (pointer) to pass-by-value, see PR #2092.

**Comment by tlimoncelli** [comment] 2023-02-22 19:59
In hindsight, it might be more time efficient (and maybe more memory efficient?) to fix it by doing:

```
func (r *record) nativeToRecord(domain string) *models.RecordConfig {
...
    heapr := r
    rc := &models.RecordConfig{
        Type:         "",
        TTL:          r.TTL,
        MxPreference: r.Priority,
        SrvPriority:  r.Priority,
        Original:     heapr,
    }
```

I don't think it is worth doing a benchmark. However it would be worthwhile adding a comment so we know to change it if becomes a performance problem. (I doubt anyone will ever notice)

**Comment by tmkis2** [comment] 2023-02-22 20:07
I can confirm https://github.com/StackExchange/dnscontrol/pull/2092 fixes my scenario. Thanks a lot to both of you!

**Comment by Yannik** [comment] 2023-02-23 00:32
@tlimoncelli why would this be faster?

**Comment by tlimoncelli** [comment] 2023-02-28 01:25
> @tlimoncelli why would this be faster?

There is less memory copying.  That said, I think the difference would be insignificant. Closing.

**Closed by tlimoncelli** 2023-02-28 01:25 UTC
